boostcampwm2023/web10-Lesser

FE/src/components/backlog/EpicBlock.tsx, FE/src/components/backlog/StoryBlock.tsx, FE/src/components/backlog/TaskBlock.tsx, FE/src/components/backlog/TaskModal.tsx, FE/src/hooks/useBlock.tsx, FE/src/pages/backlog/BacklogPage.tsx
LES-132 [FE] 유저는 백로그 전체를 확인할 수 있다.
LES-63 [FE] 에픽 목록을 화면에 렌더링 하는 코드를 작성
LES-64 [FE] 에픽 목록을 추가하는 버튼을 만든다.
LES-75 [FE] 스토리 목록을 화면에 렌더링 하는 코드를 작성
LES-76 [FE] 스토리 목록을 추가하는 버튼을 만든다.
LES-83 [FE] 태스크 목록을 추가하는 버튼을 만든다.
LES-84 [FE] 태스크 목록을 화면에 렌더링 하는 코드를 작성
칸반보드를 볼 수 있는 페이지를 생성하고 에픽, 스토리, 태스크를 추가할 수 있는 코드를 작성하였습니다.
- 태스크 목록을 추가하는 기능까지 구현했고, 에픽 Toggle 버튼을 눌렀을 때 태스크 목록이 사라지는 경험을 했습니다. 이로 인해 useState를 사용하지 않고 전역으로 상태를 관리해야 한다는 것을 깨달았습니다.
=> 백로그 페이지 코드 작성

FE/src/components/backlog/EpicBlock.tsx, FE/src/components/backlog/StoryBlock.tsx, FE/src/components/backlog/TaskBlock.tsx, FE/src/components/backlog/TaskModal.tsx, FE/src/components/common/ProgressBar/ProgressBar.tsx, FE/src/components/sprint/BoardHeader.tsx, FE/src/components/sprint/ColumnBoard.tsx, FE/src/components/sprint/FilterDropdown.tsx, FE/src/components/sprint/KanbanBoard.tsx, FE/src/components/sprint/TaskCard.tsx, FE/src/hooks/useBlock.tsx, FE/src/pages/backlog/BacklogPage.tsx, FE/src/pages/sprint/SprintPage.tsx, FE/src/types/sprint.ts, FE/tailwind.config.js
- LES-112 [FE] 칸반보드를 렌더링하는 코드를 작성한다.
- 지정된 디자인에 맞게 className 추가
- 필터링하는 드롭다운 메뉴 컴포넌트 생성 및 필터 기능 추가
- 보드 크기를 고정해놔서 사이 간격이 넓습니다. 나중에 사이드 바를 추가하면서 스타일을 수정하려 합니다.
- twin.macro를 사용하려고 했는데 어떤 이유에서인지 동작을 하지 않아서 어떤 점이 문제가 되는 것인지 더 알아봐야 할 것 같습니다. 스타일 코드보다는 기능이 더 중요하다고 생각해 일단 스타일은 모두 className에 tailwind를 사용해 정의했습니다.
- 빨리 문제를 찾고 적용해 중복되는 부분을 줄여야 할 것 같습니다.
- 어떤 컴포넌트를 styled component로 만들 것인지도 더 고민해봐야 할 것 같습니다.
- 생각보다 같은 타입을 지정해줘야 하는 부분이 많아서 잘 사용하고 있는지 의문이 들었습니다.다.
``` typescript
// state 정의할 때 타입 지정
const [taskGroup, setTaskGroup] = useState<TaskGroup>('all');
// 해당 state를 변경하는 함수의 매개변수 타입 지정
const handleGroupButtonClick = (taskGroup: TaskGroup): void => {
setTaskGroup(taskGroup);
setDropdownOpend(false);
};
// 해당 state를 props로 받는 곳에서 타입 지정, 해당 state를 변경하는 함수를 props로 전달할 때 그 함수의 매개변수 타입 지정
interface …
```
=> 칸반보드 렌더링 코드 작성

BE/package.json, BE/src/backlogs/backlogs.controller.ts, BE/src/backlogs/backlogs.service.ts, BE/src/dto/create-backlogs-epic-response.dto.ts, BE/src/dto/create-backlogs-story-response.dto.ts, BE/src/dto/create-backlogs-task-response.dto.ts, BE/test/app.e2e-spec.ts, BE/test/jest-e2e.json
태스크 없음
1. 에픽, 스토리, 태스크 생성의 리턴을 빈 객체에서 식별자로 변경
2. RESPONSE DTO정의
1. API/backlogs/task의 수정메서드가 PATCH로 되어있어야 하는데 PUT으로 되어있어 수정
1. e2e테스트 경로설정
2. e2e --watch 명령어 추가
1. epic, story, task의 CREATE, PUT/PATCH, DELETE에 대해 테스트코드를 추가하였다.
=> 백로그 API 수정, 백로그 테스트코드 작성

BE/src/backlogs/backlogs.controller.ts, BE/src/backlogs/backlogs.service.ts
LES-138 NestJS 서버를 Jenkins로 자동 빌드, 도커 컨테이너로 올리기
원격에서 NestJS 서버 빌드시 './dto/epic.dto' 모듈을 찾을 수 없다는 오류가 발생, './dto/Epic.dto'로 수정하였습니다.
=> 백엔드 서버 import 경로 오타 수정

BE/src/backlogs/backlogs.controller.ts, BE/src/backlogs/backlogs.service.ts, BE/src/backlogs/dto/backlog.dto.ts, BE/test/backlogs.e2e-spec.ts
LES-163 [BE] 프로젝트의 백로그데이터를 전달한다.
task: [BE] 프로젝트의 백로그데이터를 전달한다.
1. RESPONSE DTO정의
2. /backlogs/[id]경로에 서비스, 컨트롤러 매핑
3. 프로젝트 없을경우 404처리
4. 있을경우 데이터 만들어서 반환
1. 프로젝트로 백로그 찾는 테스트 작성
* 백로그를 찾는 API를 작성했습니다. id에 대한 유효성검사는 parseIntPipe로 했습니다.
* 백로그 데이터를 만들기위해 DB에 select를 많이 해야해서 이 부분을 조금 신경써서 Promise.all로 처리했습니다. 비효율적인 부분이나, 더 괜찮은 방법이 있으면 말씀해주시면 좋을것같아요 !
=> 백로그 확인 API 작성 (/api/backlogs/{projectId})

FE/src/components/backlog/NavigationButton.tsx, FE/src/components/backlog/SideNavigationBar.tsx, FE/src/components/sprint/BoardHeader.tsx, FE/src/components/sprint/ColumnBoard.tsx, FE/src/components/sprint/TaskCard.tsx, FE/src/pages/MainPage.tsx, FE/src/pages/SprintPage.tsx
- [LES-164] 네비게이션 바 디자인 적용
- [LES-112] 칸반보드 렌더링 코드 작성
- 칸반보드 페이지 width를 고정시켰습니다.
- 컬럼 보드와 태스크 카드 테두리 색 변경했습니다.
- 사이드 네비게이션 바의 높이가 항상 화면의 위, 아래와 32px 떨어지도록 고정했습니다.
- 스크롤이 생겨도 사이드 네비게이션 바의 위치는 고정되도록 했습니다.
=> 칸반보드 및 네비게이션 바 디자인 수정

BE/src/projects/dto/Project.dto.ts, BE/src/projects/entity/project.entity.ts, BE/src/projects/projects.controller.ts, BE/src/projects/projects.service.ts
1. 기존의 프로젝트를 모두 가져옴
2. 추후 유저별로 찾도록 구현을 추가해야함
1. project엔티티에 subject추가
2. DTO에 subject 추가
3. 서비스에 subject로직 추가
* GET /api/backlogs에서 기존 프로젝트 읽기를 데모이슈로 빠르게 구현했습니다.
* 우선 전체데이터를 보내게 해 놓았고, nextPage는 backlogs로 하드코딩해놓았습니다.
* project에 subject를 추가하는 요구사항을 알게되어서 추가해놓았습니다.
* 항상 감사합니다 ~
=> /api/backlogs 기존 프로젝트 읽기 API작성

BE/src/app.module.ts, BE/src/members/dto/login-request.dto.ts, BE/src/members/dto/member.dto.ts, BE/src/members/entities/member.entity.ts, BE/src/members/members.controller.ts, BE/src/members/members.module.ts, BE/src/members/members.service.ts
LES-168 [BE] 깃허브 OAuth 회원가입
LES-169 [BE] 깃허브 OAuth 로그인
- 로그인 API 구현: POST `/api/members/login`
- 클라이언트로부터 auth code 값을 받아서 깃허브 Access Token 받아온다.
- 깃허브 Access Token 사용하여 깃허브 API로 유저 정보를 요청해서 가져온다.
- 우리 서비스의 회원인지 확인한다. 현재 로직에서는 회원이면 로그인, 회원이 아니면 회원가입
- 우리 서비스의 `Lesser Access Token`, `Lesser Refresh Token` 발급하여 클라이언트에게 반환한다.
- 우리 서비스 회원이 아닐시 회원가입하는 부분을 함수로 따로 빼는 것이 좋을 것 같다.
=> feat: [user-login] 깃허브 OAuth 회원가입/로그인

FE/src/components/backlog/TaskBlock.tsx, FE/src/hooks/useBlock.tsx
- 백로그 페이지 에픽 제목 수정과 스토리 생성을 동시에 할 수 없도록 수정
- 태스크를 수직으로 가운데 정렬하고 태스크 편집 폼, 담당자, 포인트 width 고정
=> 백로그 페이지 버그 및 디자인 수정

FE/jest.config.ts, FE/jest.setup.ts, FE/package.json, FE/src/test/sample.test.ts, FE/tsconfig.json, FE/yarn.lock
[LES-165] [FE] Jest 환경 설정을 진행한다.
1. jest 설치
2. vite 내 jest 설정
- jest 설정 후 샘플 테스트 실행 결과
- 샘플 테스트
```typescript
const sum = (a: number, b: number): number => a + b;
test('샘플 테스트 실행', () => {
expect(sum(1, 2)).toBe(3);
});
```
- 테스트 결과
=> chore: jest 환경 설정 완료

BE/src/members/dto/tokens.dto.ts, BE/src/members/members.controller.ts, BE/src/members/members.service.ts
1. 로그인하면 메모리에 refresh token(key), 회원 id(value)를 Map 구조에 저장
2. 로그아웃하면 메모리의 회원 로그인 정보 삭제
3. 리프레쉬 요청시 기존 로그인 정보 삭제, 새로 발급한 refresh token으로 로그인 정보 저장
=> 로그인 회원 정보를 메모리에 저장, 로그아웃 및 토큰 리프레쉬 구현

FE/src/apis/api.ts, FE/src/hooks/useLogin.ts, FE/src/vite-env.d.ts
다음 값들을 환경변수로 설정
- `VITE_NEST_API_URL`: nest api 요청 주소
- `VITE_GITHUB_OAUTH_URL`: 깃허브 oauth 요청 주소
- `VITE_GITHUB_CLIENT_ID`: 깃허브 클라이언트 아이디
프론트엔드 도커 컨테이너 빌드 과정에서 환경변수를 넣도록 Jenkins 설정을 수정하였습니다.
=> FE 환경변수 설정

BE/src/backlogs/backlogs.controller.ts, BE/src/backlogs/backlogs.module.ts, BE/src/backlogs/backlogs.service.ts, BE/src/backlogs/backlogsAuth.service.ts, BE/src/members/entities/member.entity.ts, BE/src/projects/entity/project.entity.ts, BE/src/projects/projects.controller.ts, BE/src/projects/projects.service.ts
LES-151 [BE]유저가 가지고있는 프로젝트의 목록을 반환한다.
LES-150 [BE] 프로젝트 데이터가 유효하지 않거나 권한이 없을때 실패한다
LES-68 [BE] 에픽생성이 실패했을때 실패이유를 반환한다.
LES-71 [BE] 스토리 생성이 실패했을때 실패이유를 반환한다.
LES-74 [BE] 태스크 생성이 실패했을때 실패이유를 반환한다.
엔티티와 연동
1. 멤버, 유저 엔티티에 반대편 엔티티와 멤버 명시
2. 프로젝트 추가할 때 유저-프로젝트 테이블에 유저 + 프로젝트 정보 추가하도록 변경
3. 프로젝트 조회시 유저의 프로젝트만 조회할 수 있도록 변경
1. 백로그에 백로그 인가하는 서비스생성
2. 프로젝트 존재여부, 프로젝트 인가가능 확인해 
적절한 에러를 던짐
1. backlogAuth 서비스에 프로젝트, 에픽, 스토리, 태스크 인가로직 작성
2. 컨트롤러 엔드포인트 각각에 데이터 형태에 맞는 인가서비스 사용
* 프로젝트 생성시 로그인 한 멤버가 프로젝트-멤버 테이블에 추가되게 했습니다.
* 프로젝트 조회시 로그인 한 멤버의 프로젝트만 조회되도록 했습니다.
* 백로그(에픽, 태스크, 스토리) 접근시 권한을 확인하게 했습니다.
* 백로그에서 사용자가 접근하는 리소스가 없는지 혹은 권한이 없는지를 구분하지 못하게 403 forbidden으로 통일했습니다.
* 항상감사합니다.
=> 프로젝트, 백로그 유저 인가

FE/src/components/sprint/ColumnBoard.tsx, FE/src/components/sprint/KanbanBoard.tsx, FE/src/components/sprint/TaskCard.tsx, FE/src/data/sprint.json, FE/src/hooks/useKanbanDrag.tsx, FE/src/pages/SprintPage.tsx, FE/src/types/sprint.ts
- [LES-185] 드래그 앤 드롭을 구현한다.
- 칸반보드에서 드래그 앤 드롭을 구현했습니다.
- Drag and Drop API를 이용해서 dragEvent를 통해 구현했습니다.
- 다른 스토리 그룹의 보드로 이동하지 못하도록 했습니다.
- 아직 API가 없어서 data 폴더에 데이터를 넣어 놓고 axios로 가져와서 state에 저장해주는 방식으로 진행했습니다.
- 드래그 앤 드롭 기능을 넣으면서 ColumnBoard에 전달해야 할 프롭들이 더 생겨났는데, KanbanBoard 자체에서 사용하는 props보다 ColumnBoard로 넘겨주는 props들이 더 많아져서 children을 이용하는 방식으로 변경했습니다. 두 단계만 내려가면 되기는 하지만 최대한 props만 전달하게 되는 걸 줄이고자 이렇게 했습니다.
=> 칸반보드 드래그 앤 드롭 구현

BE/src/backlogs/backlogs.module.ts, BE/src/backlogs/backlogs.service.ts, BE/src/backlogs/dto/backlog.dto.ts, BE/src/backlogs/dto/baseType.dto.ts, BE/src/backlogs/entities/task.entity.ts, BE/src/common/decorators/IsNullOrIntDecorator.ts, BE/src/projects/dto/Project.dto.ts, BE/src/projects/projects.service.ts
LES-92 [BE] 태스크의 담당자를 추가, 수정할 수 있다.
1. readProjectListResponseDTO에 유저DTO추가
2. 프로젝트 서비스에서 프로젝트 목록 조회시 유저정보 함께 넘기게 추가
1. 태스크 API에 userId제약조건을 notempty, int or null로 변경
2. 백로그조회시 태스크의 담당자의 아이디를 반환하도록 변경
3. 태스크 추가시 태스크의 담당자정보를 null or int로 받도록 추가
4. 태스크 수정시 태스크의 담당자정보를 다룰수있도록 변경
* 태스크 담당자 추가 OR 수정시 해당 담당자가 프로젝트의 소속인지 확인하는 로직이 필요합니다.
* 트러블 냉장고에 넣어놓았고, 주말중에 수정하겠습니다.
* 항상감사합니다.
=> 프로젝트, 백로그 API를 멤버와 연동

BE/src/backlogs/backlogs.module.ts, BE/src/backlogs/backlogs.service.ts, BE/src/backlogs/dto/Epic.dto.ts, BE/src/backlogs/dto/Story.dto.ts, BE/src/backlogs/dto/Task.dto.ts, BE/src/backlogs/dto/backlog.dto.ts, BE/src/backlogs/dto/baseType.dto.ts, BE/src/backlogs/entities/epic.entity.ts, BE/src/backlogs/entities/story.entity.ts, BE/src/backlogs/entities/task.entity.ts, BE/src/projects/entity/projectCounter.entity.ts, BE/src/projects/projects.module.ts, BE/src/projects/projects.service.ts
1. 프로젝트와 1대1 대응인 projectCounter 테이블 추가
2. 프로젝트 생성시 카운터테이블 같이 생성
3. 백로그DTO에 순서정보 추가
4. 백로그 생성시 projectCounter 정보 갱신후 순서정보 응답
4. 백로그 리스트 요청시 순서정보 함께 응답
상세내용 없습니다.
* 유저에게 노출되는 숫자를 저장해 사용하는 projectCounter 테이블을 추가했습니다.
* 매번 에픽, 스토리, 태스크의 개수를 계산하면 비효율적인것 같아 테이블을 하나 더 만들었습니다.
* 항상 감사합니다
=> 백로그 sequence 데이터 추가

BE/src/reviews/dto/Review.dto.ts, BE/src/reviews/dto/SprintReviewResponse.dto.ts, BE/src/reviews/reviews.controller.ts, BE/src/reviews/reviews.module.ts, BE/src/reviews/reviews.service.ts, BE/src/sprints/entities/sprint-task.entity.ts
[LES-215] 프로젝트 id를 받으면, 종료된 스프린트 목록(생성일과 종료일, 실제 종료일 포함), 각 스프린트의 (태스크 목록,  스프린트 목표, 스프린트 기간)을 전송하는 API
[LES-228] 회고 데이터를 전달하는 API
회고 페이지 조회시 필요한 스프린트, 태스크, 회고글 정보를 가져오는 API를 만들었습니다. 스프린트, 스프린트-태스크, 태스크 테이블을 Join하여 스프린트에 포함된 태스크 정보를 가져옵니다.
=> 회고 페이지 조회 API 작성

BE/src/projects/dto/GetSprintProgressRequest.dto.ts, BE/src/projects/entity/project.entity.ts, BE/src/projects/projects.controller.ts, BE/src/projects/projects.module.ts, BE/src/projects/projects.service.ts, BE/src/sprints/entities/sprint.entity.ts
LES-183 스프린트 단일조회 API 노출하기
1. 스프린트 엔티티의 project_id의 조인 없는 사용을 위해 joinColumn으로 이름 지정하고, 컬럼생성
2. DTO생성
3. progress인지 체크 후, 분기해서 응답
* 스프린트 종료 로직 작성 후 변경되는 로직에 대해 주석으로 표시해 놓았습니다.
* 종료가 안된 스프린트에 대해 end-date 이후 요청에 대해 스프린트 종료처리하게 됩니다.
*  조인 부분 관련해서 리펙토링 예정입니다.
* 현재 task의 member 엔티티참조입니다. 프로퍼티로 task는 있으나, taskId가 없어 실제 테이블은 taskId를 가지고 있으나 조인을 해야지만 task.member.id 로 참조할 수 있음
=> feat: [kanban-task-read] 현재 진행하고 있는 스프린트 응답

FE/src/apis/api.ts, FE/src/components/common/ProgressBar/ProgressBar.tsx, FE/src/components/sprint/BoardHeader.tsx, FE/src/components/sprint/ColumnBoard.tsx, FE/src/components/sprint/TaskCard.tsx, FE/src/pages/SprintPage.tsx, FE/src/types/sprint.ts
- [LES-186] 태스크를 클릭했을 때 태스크 디테일 모달을 띄운다.
- [LES-191] 태스크 수정 API를 연동한다.
- [LES-181] API 연동을 통해 태스크 데이터를 가져오고 화면에 보여준다.
- 요청이 실패할 때마다(401이 아니더라도) refresh 토큰을 삭제하던 것을 401에러가 뜨거나, 토큰 갱신에 실패했을 때만 삭제하는 것으로 수정했습니다.
- react-query를 이용해 데이터를 가져오고 수정하도록 연동했습니다.
- 이미 완성된 모달 컴포넌트를 사용해 태스크 모달을 띄울 수 있도록 했습니다.
=> 토큰 refresh 로직 수정, 칸반보드 API 연결, 칸반보드 모달 연결

BE/src/projects/dto/GetSprintProgressRequest.dto.ts, BE/src/projects/projects.service.ts, BE/src/sprints/dto/Sprint.dto.ts, BE/src/sprints/sprints.controller.ts, BE/src/sprints/sprints.service.ts
LES-183 진행중인 스프린트 조회 API 노출하기
LES-282 스프린트 종료 API 작성하기
1. 스프린트번호로 스프린트를 종료한다.
2. 유저권한체크는 추후에 구현
* GET요청으로 실제 데이터가 변경되게 하는것이 맞나 ? 이런 생각이 듭니다.
* 스프린트의 종료조건이 직접 종료하거나, 설정시간 이후면 자동으로 종료되는건데, 종료시간 이후 진행스프린트 조회시 서버에서 스프린트 종료처리를 하게 됩니다.
* 이 부분을 REST하기 위해서는 현재 GET을 받았을 때 종료처리를 하는게아니라, 프론트에서 한번 더 종료요청을 보내는게 더 적절한것 같습니다.
* 항상 감사합니다.
=> 스프린트 종료 API, 진행중인 스프린트 조회 API 수정

BE/src/common/types/githubResource.type.ts, BE/src/members/dto/github-user.dto.ts, BE/src/members/dto/member.dto.ts, BE/src/members/members.controller.ts, BE/src/members/members.service.ts
[LES-281] 회원 조회 API
- GET method
- URI: /members/search?username={username}
- 회원 엔티티의 username(깃허브 계정 닉네임)으로 검색
- TypeORM의 ILike 사용(대소문자 구분x), % 와일드카드 사용하여 검색어를 일부 포함한 모든 회원 검색
```ts
const members = await this.memberRepository.find({ where: { username: ILike(`%${username}%`) } });
```
=> 회원 닉네임(username)으로 조회하는 API 구현

BE/src/projects/dto/Project.dto.ts, BE/src/projects/projects.service.ts
=> 프로젝트 조회시 멤버정보로 깃허브 아이디 반환, 프로젝트 생성시 멤버리스트 함께 요청받음

FE/src/components/review/DonutChart.tsx, FE/src/components/review/ReviewChart.tsx, FE/src/components/review/ReviewHeader.tsx, FE/src/components/review/ReviewReminiscing.tsx, FE/src/components/review/ReviewSprint.tsx, FE/src/hooks/pages/review/useReminiscing.tsx, FE/src/pages/ReviewPage.tsx, FE/src/types/review.ts, FE/src/utils/date.ts
- [LES-220] 드롭다운에서 다른 스프린트를 클릭하면 /review 페이지에서 바뀐 스프린트 정보를 보여준다.
- [LES-224] 작성된 회고가 있다면 작성된 회고를 보여준다.
- [LES-225] 작성된 회고는 textarea 비활성화 상태를 보여준다.
- [LES-226] 작성된 회고가 없으면 스프린트에 대해 회고하라는 메시지를 보여준다.
- [LES-227] 작성된 회고가 없다면 "작성하기" 버튼을 보여주고, 작성된 회고가 있다면 "수정하기" 버튼을 보여준다.
- [LES-230] textarea 활성화되고 회고를 입력할 수 있다.
- [LES-231] 완료 버튼을 클릭하면 작성된 회고를 저장하도록 API 요청하고, 요청 성공시 작성된 회고를 화면에 보여준다.
- [LES-234] textarea 활성화되고 회고를 입력할 수 있다.
- [LES-235] 완료 버튼을 클릭하면 수정된 회고를 저장하도록 API 요청, 요청 성공시 수정된 회고를 화면에 보여준다.
- [LES-237] 유저는 작성/수정 취소 버튼을 클릭하면 회고 생성/수정 이전의 상태로 돌아간다.
스프린트 리스트 드롭다운에서 다른 스프린트를 클릭하면 회고 페이지에서 바뀐 스프린트 정보를 출력합니다.
회고란 탭에서 회고를 작성하고 작성된 회고를 수정할 수 있는 기능을 구현하였습니다.
스프린트 정보 탭에서 데이터가 없을 때, 태스크의 완료 및 미완료 목록과 도넛 차트가 더 나은 형태로 표시되도록 개선하였습니다.
번다운 차트의 더 정확한 표현을 위해 'ideal' 데이터 포인트를 소수점 3자리까지 표시하도록 조정하였습니다.
=> 회고란 탭 기능 구현

BE/src/members/dto/member.dto.ts, BE/src/projects/dto/Project.dto.ts, BE/src/projects/projects.controller.ts, BE/src/projects/projects.service.ts
[LES-280] 프로젝트 회원초대 API
- 프로젝트 id와 추가할 회원 id 리스트를 받고, 해당 프로젝트의 구성원 목록에 회원을 추가한다.
- 이미 프로젝트 구성원 목록에 있는 회원은 제외하여 추가한다.
```ts
const projectMemberIdList = project.members.map((member) => member.id);
const newMemberIdList = dto.memberList.filter((memberId) => !projectMemberIdList.includes(memberId));
const newMembers = await this.memberRepository.find({ where: { id: In(newMemberIdList) } });
```
=> 프로젝트 회원 추가 API 구현

FE/src/components/review/ReviewHeader.tsx, FE/src/components/review/ReviewReminiscing.tsx, FE/src/components/review/ReviewSprint.tsx, FE/src/constants/constants.tsx, FE/src/hooks/pages/review/useReminiscing.tsx, FE/src/pages/ReviewPage.tsx, FE/src/types/review.ts
- reviewTabs 변수 constants에서 관리하도록 수정
- remi -> reminiscing 풀네임으로 수정
- reminiscing의 초기값을 useEffect를 통해 변경하도록 수정
- task 완료, 미완료 목록 TaskComponent 재사용
- 회고란을 수정할 때 이전 값과 비교해서 같으면 요청을 보내지 않도록 수정
=> 회고 페이지 리팩토링

FE/src/hooks/pages/useLogin.tsx, FE/src/hooks/pages/useLogout.tsx, FE/src/stores/index.ts, FE/src/stores/useUserState.ts
- 로그인 시, 서버로 username과 id를 전달받고 해당 데이터를 zustand를 사용하여 전역 상태로 관리
1. zustand에 사용자 정보를 저장하기 위한 useUserState 생성
2. login 시, 전달 받는 id, username을 useUserState에 저장
3. logout 시, 전달 받는 id, username을 초기화
- 사용자가 새로고침을 하더라도 데이터 초기화를 막기 위해 useUserState의 데이터를 localStorage에 저장하여 관리
=> 유저 로그인 시, 유저이름과 id를 전역 상태로 관리

FE/src/components/project/ProjectCard.tsx, FE/src/components/project/ProjectInviteForm.tsx, FE/src/constants/constants.tsx, FE/src/hooks/pages/project/useCreateNewProject.ts, FE/src/hooks/pages/project/useSearchUsername.ts, FE/src/hooks/queries/project/usePostNewProject.ts
1. 사용자의 본인의 정보를 프로젝트 생성 시, 참여자에 자동으로 추가하는 로직을 작성
- 사용자 정보(닉네임, id)를 전역에서 관리할 수 있게 되어, 본인이 생성하는 프로젝트에 자신의 정보를 자동으로 추가하는 로직을 추가
- 사용자 자신을 닉네임 검색 할 경우, 추가하지 않고 사용자에게 본인을 추가할 수 없도록 고지하는 로직을 추가
2. 복수의 인원을 추가했을 경우, 화면 스타일을 수정하는 코드 작성
=> 사용자의 본인의 정보를 프로젝트 생성 시, 참여자에 자동으로 추가하는 로직을 작성

FE/src/apis/sprint/fetchPatchSprintEnd.ts, FE/src/components/sprint/FilterDropdown.tsx, FE/src/components/sprint/KanbanBoard.tsx, FE/src/components/sprint/modal/SprintEndModal.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogSetting.tsx, FE/src/hooks/queries/sprint/index.ts, FE/src/hooks/queries/sprint/useGetProgressSprint.ts, FE/src/hooks/queries/sprint/usePatchSprintEnd.ts, FE/src/hooks/queries/sprint/usePatchTaskState.ts, FE/src/pages/SprintPage.tsx, FE/src/pages/sprint/SprintCreatePage.tsx, FE/src/types/sprint.ts
- [LES-196] 연동된 API로 받아오는 데이터에 맞게 필터링 로직을 수정한다.
- [LES-240] 드래그 앤 드롭을 통해 스프린트 백로그에 태스크 추가 기능 구현
- [LES-279] 스프린트 종료 API 연동
- 태스크 옆에 x 아이콘을 두고 클릭 시 백로그로 돌아가도록 했습니다. 
- projectState에서 useList를 가져와서 sprint 페이지 필터링에 반영되도록 했습니다.
- 스프린트 종료를 누르면 종료를 확인하는 모달이 뜨고, 해당 모달에서 종료를 누르면 종료 요청이 가고 리뷰 페이지로 이동하도록 했습니다.
- 스프린트 백로그 태스크를 제거했을 때 이전 자리로 돌아가도록 했지만 완전히 순서가 일치하도록 하지는 못했습니다.
``` typescript
// 타겟 설정 시 이전에 있던 index 기억
const targetTask: SprintBacklog = {
...backlog.epicList[epicIndex].storyList[storyIndex].taskList[source.index],
epicIndex,
storyIndex,
taskIndex: source.index,
};
// 삭제할 때 이전 인덱스를 기반으로 추가
queryClient.setQueryData(['backlogs', 1, 'sprint'], (prevBacklog: { epicList: ReadBacklogEpicResponseDto[] }) => {
const newBacklogData = structuredClone(prevBacklog); …
```
=> 스프린트 생성 시 태스크 설정 기능, 칸반보드, 스프린트 종료

FE/src/components/backlog/Modal/TaskModal.tsx, FE/src/components/backlog/Modal/TaskPostModal.tsx, FE/src/components/backlog/Modal/TaskUpdateModal.tsx, FE/src/components/backlog/TaskForm.tsx, FE/src/components/sprint/TaskCard.tsx, FE/src/types/backlog.ts
1. type을 각자 작성해서 호출하여 사용하는 문제로 인해 각자가 작성한 타입간 불일치(userId: string 혹은 number를 혼재하여 사용)
2. 해당 타입 에러의 문제를 임시로 string|number로 설정하여 리팩토링 전 임시 문제 해결
3. UpdateModal의 경우 prop으로 데이터를 전달할 때, 불필요한 "defaultData" 형태를 구성하여 전달하였기 때문에, 데이터 전달 간 타입 에러 발생
- 해당 코드에 불필요한 defaultData 형태를 제거하고, prop data를 데이터를 전달하는 형태의 타입을 재사용하여 전달
=> fix: update modal 타입 에러 수정

FE/src/App.tsx, FE/src/apis/api.ts, FE/src/components/common/NavigationButton.tsx, FE/src/components/common/PrivateRoute.tsx, FE/src/components/common/SideNavigationBar.tsx, FE/src/components/sprint/modal/SprintEndModal.tsx, FE/src/components/sprint/sprintCreate/BacklogComponent.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogSetting.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogTask.tsx, FE/src/constants/constants.tsx, FE/src/hooks/pages/useLogin.tsx, FE/src/hooks/queries/sprint/usePatchSprintEnd.ts, FE/src/hooks/queries/sprint/usePostNewSprint.ts, FE/src/pages/SprintPage.tsx, FE/src/pages/sprint/SprintCreatePage.tsx, FE/src/pages/sprint/SprintLandingPage.tsx, FE/src/types/navigation.ts
- 스프린트 생성 시 태스크를 설정할 때 태스크의 길이를 고정해 `x` 아이콘이 튀어나오지 않도록 했습니다.
- 태스크를 다른 데로 드래그 하면 스프린트 백로그에서 제거되도록 했습니다.
- 스프린트 백로그를 설정하지 않으면 설정하라는 알림을 띄우도록 했습니다.
- 로그인하지 않았을 시 login 페이지로 리다이렉트 되도록 했습니다.
- 루트페이지
- 다른 페이지
- 현재 정해진 url로 이동할 수 있도록 네비게이션에 있는 url을 수정했습니다.
``` typescript
const navigationInformation: NavigationInformation[] = [
{
pageName: '백로그',
pageURI: (projectId) => `/projects/${projectId}/backlog`,
description:
'백로그 페이지 설명. 백로그는 제품백로그와 스프린트 백로그가 있으며 에픽, 스토리, 태스크로 이루어진다.',
},
{
pageName: '스프린트',
pageURI: (projectId) => `/projects/${projectId}/sprint`,
description:
'스프린트 페이지 설명. 스프린트 시작하면 칸반보드를 확인할 수 있고, 드래그 앤 드롭을 이용해 티켓을 옮길 수 있다.',
},
{
pageName: '회고',
pageURI: (projectId) => `/projects/${projectId}/review/sprint`,
description: '회고하는 페이지 설명. 스프린트 백로그 태스트 상태 분석, 번다운 차트, 회고 글 작성 칸이 있을 예정',
}, …
```
=> 로그인 가드 구현, 태스크 설정 기능 수정

FE/src/components/backlog/Modal/BacklogDeleteModal.tsx, FE/src/components/backlog/Modal/TaskPostModal.tsx, FE/src/components/backlog/Modal/TaskUpdateModal.tsx, FE/src/constants/constants.tsx, FE/src/hooks/pages/backlog/usePostBacklog.tsx, FE/src/hooks/pages/backlog/useUpdateBacklog.tsx, FE/src/pages/project/ProjectPage.tsx
- invalidQuries의 queryKey를 ['backlog'] 하나만 설정하면 'backlog'로 시작하는 모든 query를 invalid 상태로 변경 가능
- onSuccess 의 queryKey를 상기의 방법으로 수정
- 프로젝트 생성 페이지의 url로 이동하는 코드를 수정하여 정상적으로 생성 페이지로 이동
=> fix: Backlog 생성/수정/삭제 시, 화면이 즉시 적용 되지 않는 문제 해결

FE/src/assets/icons/ChevronUpIcon.tsx, FE/src/components/backlog/BacklogTitle.tsx, FE/src/components/backlog/EpicComponent.tsx, FE/src/components/backlog/MemberDropdown.tsx, FE/src/components/backlog/Modal/TaskModal.tsx, FE/src/components/backlog/Modal/TaskPostModal.tsx, FE/src/components/backlog/Modal/TaskUpdateModal.tsx, FE/src/components/backlog/StoryComponent.tsx, FE/src/components/backlog/TaskModalItemLayout.tsx, FE/src/components/backlog/taskForm/TaskForm.tsx, FE/src/components/sprint/sprintCreate/BacklogComponent.tsx, FE/src/hooks/pages/backlog/useDropdownToggle.tsx, FE/src/hooks/pages/backlog/useGetUsername.tsx, FE/src/hooks/pages/backlog/usePostBacklog.tsx, FE/src/hooks/pages/backlog/useTaskManager.tsx, FE/src/hooks/pages/backlog/useTaskUsername.tsx, FE/src/pages/backlog/BacklogPage.tsx, FE/src/types/backlog.ts, FE/src/utils/getStoryPoint.ts
- invalidQueries의 조건을 모든 데이터에서 실행하던 내역을 'backlogs' key를 가진 query로 제한하여 데이터를 불필요하게 fetch 하는 경우를 제외
- task ponint의 최소값을 0으로 설정
- task 담당자를 미할당 하는 버튼을 작성하여, 서버에 null을 전달하는 코드를 작성
- dropdown을 열고 닫는 커스텀 훅을 작성하고, member를 확인하는 dropdown에 적용
- TaskModal의 디자인을 TaskPostModal과 일부 차이를 주도록 수정
- TaskModal의 반복되는 제목과 설명 부분을 컴포넌트화하여 재사용성을 높임
=> Fix: Backlog page 입력값 수정, Task Modal 입력 및 디자인 수정

FE/src/components/backlog/Modal/TaskUpdateModal.tsx
- task를 업데이트 할 때, 클라이언트 메모리에 저장하는 초기값이 Number(null)로 인해 0으로 저장되는 현상 발생
- 최초 값이 null로 들어오면, null로 그 이외는 Number를 통해 숫자로 저장할 수 있도록 코드를 수정
=> fix: 미할당 task가 수정 되지 않는 현상 수정

FE/src/components/common/NavigationButton.tsx
- navigation bar 버튼의 url의 조건 설정에 오류로 인한 backlog와 sprint 버튼이 동시에 활성화
- 현재 url과 버튼에 주어진 url을 특정 기준에 맞추어 나누고, 해당 배열의 값을 string화 하여 비교하는 로직으로 수정하여, 검사를 더 간단하고 명확하게 수행할 수 있도록 수정
=> fix: naviagation bar 버튼 활성화 로직 수정

FE/src/components/sprint/FilterDropdown.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogSetting.tsx, FE/src/hooks/queries/sprint/useGetProgressSprint.ts, FE/src/hooks/queries/sprint/usePatchTaskState.ts, FE/src/pages/SprintPage.tsx, FE/src/pages/sprint/SprintCreatePage.tsx, FE/src/types/sprint.ts, FE/src/utils/structureTaskList.ts
- 칸반보드 페이지에서 드롭하면 보드의 맨 마지막에 태스크가 추가되던 것을,  낙관적 업데이트를 사용해서 사용자가 지정한 순서대로 태스크가 보여질 수 있도록 수정했습니다.
- 스프린트 백로그를 설정할 때 태스크를 새로 추가하면 이미 스프린트 백로그에 넣어놓은 것까지 백로그에 생기던 문제를 해결했습니다.
```typescript
const backlog = useMemo(() => {
const newData = structuredClone(data);
if (!sprintBacklog.length) {
return newData;
}
sprintBacklog.forEach((sprintBacklogItem: SprintBacklogTask) => {
const { epicIndex, storyIndex, taskIndex } = sprintBacklogItem;
newData.epicList[epicIndex].storyList[storyIndex].taskList[taskIndex] = undefined;
});
newData.epicList.forEach((epic: ReadBacklogEpicResponseDto) => {
epic.storyList.forEach((story) => {
story.taskList = story.taskList.filter((task) => !!task);
});
});
return newData;
}, [data, sprintBacklog]);
```
- 이렇게 백로그 데이터를 불러올 때, 스프린트 백로그를 설정할 때 가져온 데이터에서 스프린트 백로그에 있는 것을 …
=> 칸반보드 패이지 수정, 스프린트 백로그 설정 기능 수정

FE/src/components/backlog/StoryComponent.tsx, FE/src/components/backlog/TaskComponent.tsx, FE/src/pages/MainPage.tsx, FE/src/pages/backlog/BacklogPage.tsx, FE/src/types/backlog.ts, FE/src/utils/getStoryPoint.ts
- 완료된 task의 경우 story point 및 task sequence에 그음줄 및 text 색상변경
- story point 표시의 경우 (미완료 task) / (완료 task) 로 표현 변경
- main 페이지의 가로 길이를 고정하여, 데이터를 fetching, loading하는 기간 동안 navigation bar가 중앙으로 이동하던 현상을 막음
=> task state가 완료가 될 시 사용자 UI 변경

FE/src/components/common/SideNavigationBar.tsx, FE/src/components/review/ReviewSprint.tsx, FE/src/types/backlog.ts
- state의 상태를 "Todo", "InProgress", "Done" 상태 이외에 string으로 정의된 곳이 있어서 이로 인해 type 정합이 맞지 않는 부분이 있음.
- 지금은 임시적으로 서버에서 받아오는 데이터의 state에 string 타입을 정의하여 해결. 추후, type 정합을 맞출 필요가 있음
=> fix : state 상태값으로 인한 빌드 실패 코드 수정

FE/src/components/sprint/TaskCard.tsx, FE/src/pages/SprintPage.tsx
- 칸반보드에서 유저별, 스토리별 필터링과 그룹화가 되지 않는 문제를 수정했습니다.
- 미할당 유저 이름이 표기되지 않는 문제를 수정했습니다.
=> 칸반보드 필터링 오류 수정, 미할당 유저 이름 표기 수정

BE/src/common/lesser-jwt/lesser-jwt.service.ts, BE/src/members/members.service.ts
서로 다른 사용자가 동시에 새로고침을 할 때 다른 사용자의 계정 정보를 받아오는 문제가 발생했다.
새로고침하면 서버로 refresh token을 보내서 새롭게 발급된 access token과 refresh token을 가져오는데, refresh token은 생성할 때 회원의 고유 정보를 넣지 않아서 토큰의 만료기한이 같으면(즉, 같은 시각에 refresh token을 요청하면) 동일한 refresh token을 발급 받게 되어 회원 식별이 정상 동작하지 않는 것으로 의심된다.
=> Refresh token 발급 로직에 회원 id 추가

FE/src/test/utils.test.ts, FE/src/utils/getStoryPoint.ts
[Task125] bug fix: 스토리 포인트가 마지막 태스크 포인트만 나오는 상황을 수정한다.
- getStoryPoint의 값이 마지막 taskPoint로 출력되는 현상이 발생
- reduce 메서드 내 acc의 값을 반환하는 삼항 조건문으로 인해 마지막 값이 출력되는 현상 발생
- acc의 값 반환하는 삼항 조건문을 수정하여 문제 해결
1. Todo 3개의 경우 테스트코드 작성 (정상)
2. Todo 2개와 Done 1개의 경우 테스트코드 작성 (정상)
3. Todo 2개와 InProgress 1개의 경우 테스트코드 작성 (정상)
=> getStoryPoint 함수가 정상적으로 출력되지 않는 현상 수정

FE/src/components/common/SideNavigationBar.tsx, FE/src/components/sprint/FilterDropdown.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx, FE/src/components/sprint/sprintCreate/SprintBacklogTask.tsx, FE/src/hooks/queries/sprint/useGetProgressSprint.ts, FE/src/pages/SprintPage.tsx, FE/src/stores/useFilterState.ts, FE/src/types/sprint.ts
- 필터링 옵션에 미할당을 추가했습니다.
- 필터링 시 필터링 되는 대상의 이름을 필터 버튼에서 확인할 수 있도록 했습니다.
- 전체 태스크인 경우 그대로 필터로 표시, 특정 유저(미할당 포함)일 경우 해당 유저 이름 표시
- 스토어를 추가해 전역으로 필터링 상태를 관리하여 다른 페이지에 갔다 오거나, 새로고침을 해도 필터링 상태가 유지되도록 했습니다.
- 태스크 제목의 길이를 고정하고 말줄임표를 넣어 제거 아이콘이 태스크 밖으로 벗어나지 않도록 했습니다.
- 스프린트 태스크 박스에서 태스크 개수가 박스 크기를 넘어가면 내부 스크롤을 할 수 있도록 했습니다.
- 네비게이션 바에서 로고를 누르면 프로젝트 목록 페이지로 이동하도록 했습니다.
=> 필터링, 태스크 설정 기능 수정

FE/src/components/common/Loading.tsx, FE/src/pages/LoginPage.tsx, FE/src/pages/SprintPage.tsx
- 로그인 화면의 크기를 다른 화면들과 같도록 조정했습니다.
- 칸반보드에서 태스크 리스트가 없을 때(스프린트가 시작되지 않았거나 끝났을 때) 오류가 나 페이지가 보이지 않던 문제를 수정했습니다.
- 로딩 컴포넌트의 가로 정렬을 추가했습니다.
=> 로그인 화면 크기 조정, 스프린트 페이지 오류 수정

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts
- 컨트롤러에서 URL 값을 단순 string이 아닌 다음과 같은 형식으로 반환하도록 수정
```
{
authUrl: "https://github...."
}
```
=> fix: GitHub OAuth URL 반환하는 컨트롤러가 URL 값을 JSON 형식으로 반환하도록 변경

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts
- tempId 토큰을 보내는 상태코드를 204에서 209로 변경
- 204 상태코드에서 정상적으로 리턴했음에도 상태코드의 특성으로 인해 body가 클라이언트로 전달되지 않아 209로 변경함.
=> fix: tempId 토큰을 보내는 상태코드를 204에서 209로 변경

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts
- API 테스트시 에러 메시지를 확인할 수 있도록 auth controller에서 에러 메시지를 로그하도록 변경
=> feat: auth controller에서 에러 메시지를 로그하도록 변경

backend/src/app.module.ts, backend/src/auth/auth.module.ts, backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/entity/loginMember.entity.ts, backend/src/auth/repository/loginMember.repository.ts, backend/src/auth/service/auth.service.spec.ts, backend/src/auth/service/auth.service.ts
[로그아웃 API 구현 (POST /auth/logout)](https://plastic-toad-cb0.notion.site/API-POST-auth-logout-86dfb24a84754912815a61cd43ed9b53)
- [LoginMember 엔티티, 레포지토리 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/ec552421df643afc05a6e14ba41febbfef1bed47)
- [로그아웃 서비스 로직 및 로그인/회원가입 시 리프레시 토큰을 저장하는 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/721d6bbccc4ec9f26804ed39b6edc89af80a9f2a)
- [로그아웃 컨트롤러 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/e7416d506a2924e61582a038b8e54cbce32a27a3)
- 회원의 로그인 상태를 저장하기 위한 엔티티
- member_id, refresh_token 값 저장
- 기존 로그인/회원가입 서비스에 리프레시 토큰 저장하는 로직 및 테스트 추가
- 로그아웃 서비스 로직 및 테스트 구현
- 로그아웃 서비스에 accessToken 전달
- 로그아웃 서비스 로직 성공시 쿠키에서 refreshToken 삭제하여 응답
- [LoginMember의 객체 생성 메서드(of)에 외래키의 엔티티인 Member 객체가 꼭 …
=> feat: 로그아웃 기능 구현

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/repository/loginMember.repository.ts, backend/src/auth/service/auth.service.spec.ts, backend/src/auth/service/auth.service.ts
[토큰 리프레시 API 구현 (POST /auth/refresh)](https://plastic-toad-cb0.notion.site/API-POST-auth-refresh-dfbe487791564fd590607d90e5737420?pvs=74)
- loginMember의 리프레시토큰을 업데이트하는 메서드 추가
- refresh토큰을 받아 새로운 refresh토큰과 access토큰을 반환하는 서비스 구현
- 리프레시 컨트롤러 로직 구현
- 쿠키 누락된 설정 추가
- 리프레시토큰을 교체하고, 새로운 엑세스 토큰과 리프레시 토큰을 반환
기존의 리프레시 토큰이 유효한지 확인
리프레시 토큰으로 식별된 회원이 로그인 상태이며 DB에 저장된 리프레시토큰이 일치하는지 확인
유효하다면 새로운 리프레시토큰과 엑세스토큰을 반환
- DB에 회원의 로그인 상태가 아니거나 저장된 리프레시토큰이 일치하지 않으면 에러를 반환
- 유효한 리프레시토큰일때 바디로 새로운 엑세스토큰을 반환하고, 쿠키로 새로운 리프레시 토큰을 반환
- 리프레시토큰이 없거나 유효하지 않은 리프레시토큰이면 401 반환
- request.cookies['refreshToken']를 사용하기 위해 쿠키파서 설치
- /auth/였던 쿠키 경로를 /api/auth/로 변경
- 레포지토리 업데이트 메서드의 매개변수로 객체를 사용할지, 프로퍼티를 사용할지 고민하고 프로퍼티를 사용하기로 결정했습니다.
[매개변수에 대한 고민](https://plastic-toad-cb0.notion.site/143c40cbb3f748e3b789005d0f3e6148)
=> feat: refresh API 구현

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts
[HTTP 응답 코드 정리](https://plastic-toad-cb0.notion.site/HTTP-0f2bb22935e943f5802504f8dd70f129?pvs=74)
1. JWT 토큰 종류에 따른 에러 메시지 분리 1-1. tempIdToken 만료: 'Expired:tempIdToken'
1-2. accessToken 만료: 'Expired:accessToken'
1-3. refreshToken 만료: 'Expired:refreshToken'
2. 로그아웃 컨트롤러에서 로그인 상태의 회원이 아닌 경우를 따로 분리하여 에러 응답 2-1. 액세스 토큰 만료가 아닌, 로그인 회원이 아닌 경우에는 'Not a logged in member' 에러 메시지 반환
3. auth controller 테스트코드 작성
401 에러가 발생하면 인증에 실패한 것이므로, 기본적으로 로그인 페이지로 리다이렉트 해야한다.
다만 토큰 만료에 따른 401 에러 발생시 예외적으로 다른 로직을 수행해야하므로, 이런 상황에 분기하여 다른 로직을 수행할 수 있도록 에러 메시지로 3가지 토큰 만료 상태를 구분할 수 있도록 변경하였다.
- 에러 메시지: `Expired:accessToken`
- 후속 조치: 리프레시 토큰 이용하여 리프레시 로직 수행
- 에러 메시지: `Expired:refreshToken`
- 후속 조치: 로그인 페이지로 리다이렉트
- 에러 메시지: `Expired:tempIdToken`
- 후속 조치: 깃허브 인증 다시 수행
- 회원 인증에 실패한 것이기 때문에 로그인 페이지로 리다이렉트
- 기존의 API 명세서는 …
=> feat: auth controller 401 에러 메시지 변경

backend/src/member/entity/member.entity.ts
[DB 회원 테이블 제약조건 설정](https://plastic-toad-cb0.notion.site/DB-93beea0011ca45fa87cd5b05cdf6455b)
- Data Mapper 패턴을 채택하여 불필요한 BaseEntity 확장 제거
- 칼럼별 type, length, nullable 제약조건 설정
- github_id, username 칼럼에 unique 제약조건 설정
- github_id, username 칼럼에 index 설정
- github_username의 최대길이가 39자이기 때문에 제약조건을 39자로 둠
- github_id와 username은 unique 제약조건이 걸려있고, 특히 username컬럼은 닉네임 중복검사 API를 통해 자주 조회될것이 예상돼 index를 걸어 놓았음
position과 tech_stack의 nullable처리를 현재는 false로 해 놓았는데, 추후에 nullable하게 변경해야합니다. member Entity 클래스의 정적메서드 중 of에서 현재는 모든 컬럼을 인자로 받아 인스턴스로 생성하는데, nullable한 컬럼이 있을때 어떻게 처리해야할지 고민해보면 좋을것 같아요!
```
mysql> desc member;
+------------------+--------------+------+-----+----------------------+--------------------------------------------------+
| Field            | Type         | Null | Key | Default …
```
=> feat: Member 엔티티 제약조건 설정

docker-compose.dev.yml, docker-compose.yml, nginx/Dockerfile.dev, nginx/Dockerfile.prod, nginx/conf/conf.d/default.conf, nginx/conf/conf.d/dev.conf, nginx/conf/conf.d/prod.conf
[배포서버 nginx에 HTTPS 인증 적용](https://plastic-toad-cb0.notion.site/nginx-HTTPS-b9c1733457a54bdaa4ef46952085da94?pvs=74)
[개발서버 nginx에 HTTPS 인증 적용](https://plastic-toad-cb0.notion.site/nginx-HTTPS-22b25c0c875c43a090cf6870605be94d?pvs=74)
- 배포서버 nginx에 HTTPS 인증 적용
- 개발서버 nginx에 HTTPS 인증 적용
[링크](https://plastic-toad-cb0.notion.site/HTTPS-57e1b6995d6e463e9350649b117d0d2d?pvs=74)에 상세히 작성해놓았습니다.
- SSL인증서의 만료기한이 3개월인데 만료기한 이후에는 SSL인증서가 유효하지 않게 됩니다. 따라서 자동으로 갱신하는 프로세스를 구축해놓으면 좋을것같습니다.
- 개발서버와 배포서버의 SSL 인증서 경로가 다르기 때문에 nginx conf파일에 차이가 있습니다. nginx의 conf파일에 환경변수 적용이 어려워 nginx conf파일, 이를 불러오는 도커파일이 두개로 쪼개져 최종적으로 두개의 파일이 더 생겨났습니다. 이를 하나로 관리할 방법을 고민해보면 좋을것 같아요👻
=> feat: 개발서버 및 프로덕션서버 HTTPS 적용

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/service/auth.service.spec.ts, backend/src/auth/service/auth.service.ts
[temp id token으로 깃허브 닉네임 반환하는 API 구현](https://plastic-toad-cb0.notion.site/temp-id-token-API-ef849b302cf6442bac18c70438ce3ead)
- [tempIdToken으로 깃허브 유저네임을 찾는 서비스 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/db3859593288a63b0a15ff8fc732fbba2785483b)
- [tempIdToken을 받아 깃허브 유저네임을 반환하는 컨트롤러 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/226b34475a90410b7d3cd6c9379a50c6b1cd3974)
- 기존에 구현되어 있는 getTempMember 서비스를 재사용하여 tempIdToken에 대응하는 임시회원 정보를 가져오고, 그중 깃허브 유저네임에 해당하는 username 속성을 반환하도록 구현
- 요청 헤더에서 Authorization Bearer 형식으로 tempIdToken을 받아서 이에 대응하는 임시회원의 깃허브 유저네임을 반환하도록 구현
- tempIdToken으로 임시회원을 조회하는 새로운 서비스 로직을 도입하는 것을 고려했지만, 기존 getTempMember 로직에서 이미 토큰의 유효성 검증 등 필요한 로직이 구현되어 있었기 때문에 이를 재사용하기로 결정했습니다. 
- 또한, getTempMember 서비스는 임시회원 테이블의 pk인 uuid 값으로 조회하므로, …
=> feat: 깃허브 유저네임 반환하는 API 구현

backend/src/member/controller/member.controller.spec.ts, backend/src/member/controller/member.controller.ts, backend/src/member/member.module.ts, backend/src/member/repository/member.repository.ts, backend/src/member/service/member.service.spec.ts, backend/src/member/service/member.service.ts
[닉네임 사용 가능 여부 확인 API 구현](https://plastic-toad-cb0.notion.site/API-e37a9a0daa044b2e8d19ce434f3a446e?pvs=74)
- Member모듈 username의 유효성검사 서비스
- Member모듈 availability username 컨트롤러
- repository에 username으로 member 검색하는 메소드 추가
- service에 username을 인자로 받아 중복된 username이 있는지 검사하는 메소드 추가
- username 중복시 'duplicate username' throw함
- username 유효성 검사 컨트롤러 구현
- 유효시 {available: true} 반환
- 유효성 검사 실패시 {available: false, massage: 에러 메시지} 반환
- 일반적으로 사용할 수 있도록 서비스의 이름을 validateUsername이라고 지었습니다. 
- 이후 username에 대해 검증할 사항이 늘어났을때 이름 중복검사 뿐만 아니라, 이전에 이야기한 '조ㅇㅇ'같이 자음, 모음이 모두 같추어지지 않은 한글 닉네임도 서비스 로직에서 유효성검사하고 실패시 throw + 적절한 에러메시지를 던지게 일관적으로 구현하면 좋을것같습니다.
- void 반환형을 확인하는 테스트코드입니다. 이전에 사용한 적이 없어 첨부합니다.
```
await expect(
memberService.validateUsername(username),
).resolves.toBeUndefined();
```
=> feat: username 사용가능한지 확인(availability)하는 기능 구현

backend/package.json, backend/test/app.e2e-spec.ts, backend/test/auth.e2e-spec.ts, backend/test/jest-e2e.json
[authController E2E 테스트 코드 작성 (github/authorization-server)](https://plastic-toad-cb0.notion.site/authController-E2E-github-authorization-server-8ec828d5ed144e649af7009a9621f0ce)
- [e2e 테스트 파일에서 절대경로 찾을 수 있도록 설정](https://github.com/boostcampwm2023/web10-Lesser/commit/cbf93e73eda8b65375524f303118a21f3792783d)
- [e2e 테스트코드 설정](https://github.com/boostcampwm2023/web10-Lesser/commit/9824be30ad6ab6038cd4fe33a2f0635dcb77ce9e)
- [e2e 테스트 실행시 테스트들이 동기적으로 실행되도록 변경](https://github.com/boostcampwm2023/web10-Lesser/commit/4e843e6ed025050381ec53b4baf7d2b35fbb6394)
- jest-e2e.json
```json
"moduleNameMapper": {
"^src/(.*)$": "<rootDir>/../src/$1"
}
```
- supertest의 request를 사용해 HTTP 요청을 생성하고 response 값에 대한 검증을 수행
- beforeEach 함수를 사용하여 테스트 전에 데이터베이스의 모든 테이블 레코드를 삭제
- afterAll 함수를 사용하여 테스트 후 app 종료
- e2e …
=> test: 백엔드 e2e 테스트 생성

backend/src/auth/controller/auth.controller.ts, backend/src/member/controller/member.controller.ts, backend/src/member/member.module.ts, backend/src/member/repository/member.repository.ts, backend/src/member/service/member.service.spec.ts, backend/src/member/service/member.service.ts, backend/test/auth/github-authentication.e2e-spec.ts, backend/test/member/get-member.e2e-spec.ts, backend/test/setup.ts
[회원의 공개 정보를 응답하는 API 구현(백엔드)](https://plastic-toad-cb0.notion.site/c71cd40eb7234c549a9673bca3de1be2?pvs=74)
[test: GET /api/member API에 대한 E2E 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/d1cca18420795a7aef905c54d6ca2339185ca023)
[feat: 회원 정보 가져오는 컨트롤러 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/f36006e5804258fb50f5d5691afbc336d8819b77)
[feat: 엑세스토큰으로 회원의 공개된 정보를 반환하는 서비스 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/d8fc96a96f906099f0f6a71367baa26b6f5c2c2a)
- 유효한 엑세스 토큰일때 회원의 username과 imageUrl을 반환
- authorization 헤더가 없을때 401에러를 반환
- authorization 헤더의 포맷이 적절하지 않을때 401에러를 반환
- 엑세스토큰의 유효하지 않을때 401에러를 반환
- 엑세스토큰이 유효할때 회원정보를 가져와 반환
- 헤더의 포맷이 유효하지 않으면 401에러 반환
- id를 통해 회원의 정보를 조회하는 레포지토리 구현
- 엑세스토큰의 id로 회원의 정보를 조회해 공개된 정보를 반환하는 서비스 구현
- 레포지토리의 …
=> feat: 회원의 공개된 정보를 반환하는 /api/member API 구현

backend/src/auth/controller/auth.controller.spec.ts, backend/src/auth/controller/auth.controller.ts, backend/test/auth/github-authentication.e2e-spec.ts
- [로그인 상황에서 Authentication API가 액세스 토큰과 함께 회원의 공개 정보를 반환하도록 구현(백엔드)](https://plastic-toad-cb0.notion.site/Authentication-API-0355d7a665b44abd934c0d2811316b25)
- [POST /api/auth/github/authentication에 대한 e2e 테스트 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/7f4446a40d2ecf2e4aba6a4e96370cb1a361b1b5)
- [e2e 테스트 추가된 컨트롤러에 대하여 단위 테스트 삭제](https://github.com/boostcampwm2023/web10-Lesser/commit/f51bc7145cd2c8d85348bb8bd52057dfaac637a9)
- [회원인 사용자가 인증하는 경우 회원의 공개 정보를 body에 반환하는 기능 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/f765c91eae9c24b6c9c0c4f576f324daa6e7eb93)
- response body가 회원의 공개 정보를 포함하는지 테스트
- response cookie가 refreshToken을 포함하는지 테스트
- refreshToken 값이 jwt 패턴에 매치되는지 테스트
- 컨트롤러에 대한 단위 테스트는 e2e 테스트 추가에 따라 deprecate 하기로 결정
- 컨트롤러는 API 명세와 일치한 응답을 반환하는지 테스트하는 것이 …
=> feat: 로그인 상황에서 Authentication API가 액세스 토큰과 함께 회원의 공개 정보를 반환하도록 구현

frontend/package.json, frontend/src/App.tsx, frontend/src/AppRouter.tsx, frontend/src/GlobalErrorBoundary.tsx, frontend/src/constants/path.ts, frontend/src/pages/ErrorThrowPage.tsx, frontend/src/pages/TempHomepage.tsx, frontend/src/pages/error/ErrorPage.tsx, frontend/src/pages/index.ts, frontend/yarn.lock
[태스크 이름](해당 태스크 노션 링크)
- react-error-boundary 적용
- react-error-boundary가 에러를 잡아내지 못하는 문제 해결
- 지난 버전1의 LESSER에는 에러를 잡아내는 기능이 전무했습니다. 그저 Auth가 있는지 확인하고 이를 직접 명령적 코드를 통해 redirect 시키는 코드가 전부였습니다. 이러한 형식의 문제점은, 우리의 프로젝트에 특정 문제가 발생했을 때 사용자에게 문제가 발생했다는 것을 알려주지 못하고, 동시에 에러사항의 화면을 그대로 보여준다는 점이었습니다. 사용자에게 네트워크 문제가 발생했다고 가정했을 경우, 사용자는 아무런 조치도 못한채 텅빈 화면만을 봐야 한다는 것이었습니다.
- 이러한 문제를 해결하기 위해, Error Boundary를 도입하기로 결정했습니다. Error Boundary는 몇가지 기능을 제공하지만 그중 핵심 기능은, 에러가 발생했을 경우 자동으로 우리가 커스텀한 에러 페이지를 화면에 대신 띄워줄 수 있다는 점입니다.
- 또 강력한 기능은, 에러 로깅을 위한 개발자 툴을 사용하기에 용이하다는 점입니다. Error Boundary의 prop중 onError에 sentry와 같은 에러 로그 툴을 호출할 수 있도록 기능이 설계되어 있어 추후 프로젝트의 운영 간 발생하는 사용자의 클라이언트 로그를 쉽게 확인하고 문제분석에 더 높은 효율성을 제공할 수 있을 것입니다.
- react-error-boundary를 화면에 적용한 후, 임시 화면에서 error를 일부러 던지는 화면으로 이동할 경우, 정상적으로 (임시로 작성한) 에러페이지가 뜨는 …
=> [feat] error boundary 적용하기

backend/fixtures/project-fixtures.ts, backend/src/app.module.ts, backend/src/project/project.controller.ts, backend/src/project/project.module.ts, backend/test/jest-e2e.json, backend/test/project/get-project.e2e-spec.ts
[백엔드 프로젝트 목록 더미데이터 API 구현](https://plastic-toad-cb0.notion.site/API-ca349f4cdbfb47b9807679ad76165b72?pvs=74)
- [내 프로젝트 목록 요청시 더미데이터 반환하는 API에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/e4977ec1137f40ef72cf60df54470e412b4b1317)
- [프로젝트 더미데이터 리스트를 반환하는 GET /api/project API 컨트롤러 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/c5e047b77e37f859aba5aa5f50885f973aa70f1f)
- projectFixtures 생성
- GET /api/project 요청시 projectFixtures와 동일한 값을 반환하는지 테스트
- access token이 유효하지 않으면 401 에러 반환하는지 테스트
- 현재는 fixture에 있는 프로젝트 더미데이터를 그대로 반환
- 서비스 로직은 추후 개발 예정
- jest 테스트코드에서 객체를 비교할 때 toBe와 toEqual의 차이점에 대해 알아보았다.
- 개발일지: [객체를 toBe로 비교해도 될까?](https://plastic-toad-cb0.notion.site/toBe-91b21a6b1d2949669f753ae880f9b585)
=> feat: 프로젝트 목록 더미데이터 API 구현

backend/src/member/controller/member.controller.spec.ts, backend/src/member/controller/member.controller.ts, backend/test/auth/get-github-username.e2e-spec.ts, backend/test/member/get-member.e2e-spec.ts, backend/test/member/get-username-availability.e2e-spec.ts, backend/test/setup.ts
- [(GET) /api/auth/github/username](https://plastic-toad-cb0.notion.site/GET-api-auth-github-username-6caf5cb8dffe4820a154fb34c1a12ee7?pvs=74)
- [(GET) /api/member/availability?username={닉네임}](https://plastic-toad-cb0.notion.site/GET-api-member-availability-username-24ba2aaac792451d81a25ad37867f684?pvs=74)
- [임시회원의 깃허브 유저네임을 반환하는 API에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/b294e14408ccf389261ac31b6f7143c5034227ec)
- [닉네임 사용 가능 여부 확인 API에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/77dfa62af79ca280e1ab8c863732090535860beb)
- e2e 테스트의 setup.ts에 githubUserFixture 추가했습니다.
- 테스트 목록
- GET /api/auth/github/username 요청시 githubFixture의 유저네임과 동일한 값을 반환하는지 테스트
- authorization 헤더가 없을때 401 에러 반환
- authorization 헤더의 포맷이 적절하지 않을때 401 에러 반환
- …
=> test: 깃허브 유저네임 API, 닉네임 사용 가능 여부 확인 API에 대한 e2e 테스트

backend/test/auth/github-signup.e2e-spec.ts, backend/test/auth/logout.e2e-spec.ts, backend/test/auth/refresh.e2e-spec.ts, backend/test/setup.ts
- [(POST) /api/auth/github/signup](https://plastic-toad-cb0.notion.site/POST-api-auth-github-signup-2822735b13424dd084446bac58463580?pvs=74)
- [(POST) /api/auth/logout](https://plastic-toad-cb0.notion.site/POST-api-auth-logout-a11f434485e5416abe3ceb7d5e77ca0a?pvs=74)
- [(POST) /api/auth/refresh](https://plastic-toad-cb0.notion.site/POST-api-auth-refresh-8b0d01b9b79044b4b36baa1c71557dea?pvs=74)
- [POST /api/auth/logout 에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/90c4167fe8675fef1c614a1f18f811f7f9afa6c5)
- [POST /api/auth/github/signup 에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/9b3c15c9f4c3cdd6616c025d99cda4f98b3a59a6)
- [POST /api/auth/refresh 에 대한 e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/05388f663212c5674d35 …
=> test: auth API(회원가입, 리프레시, 로그아웃) e2e 테스트 작성

backend/src/app.module.ts, backend/src/auth/auth.module.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/entity/loginMember.entity.ts, backend/src/auth/repository/loginMember.repository.ts, backend/src/auth/repository/tempMember.repository.ts, backend/src/auth/service/auth.service.spec.ts, backend/src/auth/service/auth.service.ts, backend/src/common/middleware/parse-bearer-token.middleware.ts, backend/src/lesser-jwt/lesser-jwt.module.ts, backend/src/lesser-jwt/lesser-jwt.service.spec.ts, backend/src/member/controller/member.controller.ts, backend/src/member/member.module.ts, backend/src/project/project.controller.ts, backend/src/project/project.module.ts, backend/test/auth/get-github-username.e2e-spec.ts, backend/test/auth/github-signup.e2e-spec.ts, backend/test/auth/logout.e2e-spec.ts, backend/test/member/get-member.e2e-spec.ts, backend/test/project/get-project.e2e-spec.ts
[헤더의 토큰 처리: access token, temp id token](https://plastic-toad-cb0.notion.site/access-token-temp-id-token-583e4f05daf14f0cbee04a7b307cacf9?pvs=4)
- 사용하지 않는 import 삭제
- bearer 형식으로 들어오는 토큰을 파싱하는 미들웨어 추가
- 사용하지 않는 import 삭제
- 모듈-컨트롤러-서비스-레포지토리-DTO-엔티티-컨스턴스-미들웨어 순서로 import하도록 수정
- bearer 형식으로 들어오는 토큰을 파싱하는 미들웨어 추가
- 컨트롤러 파싱로직 수정
- bearer토큰이 들어오지 않는 경우에 대해 모두 'Bearer Token is missing' 에러메시지를 던지도록 수정
- e2e 테스트 변경
- bearer형식으로 들어오는 토큰을 파싱하는 로직이 여러차례 반복되고, 앞으로도 반복이 될것으로 예상되어서 미들웨어로 일괄적으로 파싱하게끔 작성했습니다.
- 후보로 가드, 미들웨어, 인터셉터를 생각했고 파싱로직 자체는 실행맥락에 접근할 필요가 없다고 판단해 미들웨어로 구현하게 되었습니다.
- 헤더로 bearer 토큰이 들어오는 경우에만 처리해 req.token에 넣어놓았습니다.
- 추후 가드로 인증로직을 구현하게 되면, 컨트롤러로직에서 throw 하고 있는 'Bearer Token is missing'과 'Expired:accessToken' 과 같은 인증실패에 관련된 중복로직을 많이 줄일 수 있을것 같습니다.
- [NestJS 미들웨어로 Bearer 토큰 …
=> refactor: bearer 형식으로 들어오는 토큰을 파싱하는 미들웨어 추가

frontend/jest.config.cjs, frontend/src/apis/api/loginAPI.ts, frontend/src/apis/api/projectAPI.ts, frontend/src/apis/api/signupAPI.ts, frontend/src/apis/utils/authAPI.ts, frontend/src/components/projects/ProjectCard.tsx, frontend/src/components/projects/ProjectList.tsx, frontend/src/components/projects/ProjectsSideBar.tsx, frontend/src/components/projects/index.ts, frontend/src/constants/path.ts, frontend/src/constants/projects.ts, frontend/src/hooks/common/dropdown/useDropdown.tsx, frontend/src/pages/projects/ProjectsPage.tsx, frontend/src/test/projectSortingTest.test.tsx, frontend/src/types/projectDTO.ts, frontend/src/utils/formatDate.ts, frontend/src/utils/projectSortByOption.ts, frontend/svgTransformer.cjs
- [(프로젝트 목록) 프론트엔드 화면구성](https://plastic-toad-cb0.notion.site/b98a985ea67c4d51b5048aab886f4461)
- [(프로젝트 목록) API 연결(협업)](https://plastic-toad-cb0.notion.site/API-f360093273ed4a19bfc64f25711cc470)
- [필터 함수 만들기](https://plastic-toad-cb0.notion.site/9c14249732664134b0e581d917674bfd)
- [로그아웃 API 연결(백, 프론트)](https://plastic-toad-cb0.notion.site/API-6a1c0a83e1ce455189fa1f56ffe2ae04)
- 프로젝트 목록 화면 구현
- 프로젝트 목록 API 연결
- 프로젝트 목록 필터 함수(정렬 함수) 적용
- 로그아웃 API 연결
- 디자인에 맞춰 화면을 구현했으며, 스프린트 데이터가 없는 경우에는 일단 스프린트 제목, 날짜 데이터를 보여주지 않고 흰 박스에 "스프린트 데이터가 없습니다"라는 문구가 뜨도록 했습니다.
- 피그마에 적힌 수치대로 하니 가로 화면이 남게 되어 우선 가운데에 정렬되도록 했습니다. 
- 업데이트 순으로 정렬 시 스프린트 시작 날짜가 기준이 되는데, 스프린트 데이터가 없을 경우 해당 데이터가 없는 프로젝트들은 생성일 기준 최신 순으로 정렬되도록 했습니다.
- 필터 함수는 utils에 따로 정의하지 않고 컴포넌트 내부에서 정의해서 사용했습니다. 이렇게 한 이유는 utils에 있는 함수는 여러 군데에서 재사용 할 수 …
=> feat: 프로젝트 목록 페이지 구현

backend/src/auth/controller/auth.controller.ts, backend/src/auth/service/auth.service.spec.ts, backend/src/auth/service/auth.service.ts, frontend/src/AppRouter.tsx, frontend/src/pages/login/AuthPage.tsx
[로컬 환경에서 깃허브 인증시 localhost 환경으로 리다이렉트](https://plastic-toad-cb0.notion.site/localhost-726acf5f018f4db5abc0b1579a276a08?pvs=74)
- [로컬 환경에서 깃허브 인증시 localhost 환경으로 리다이렉트 되도록 설정](https://github.com/boostcampwm2023/web10-Lesser/commit/61066125d4e9daa7f8d4fce7937131fb42d3f3f7)
- [request.headers.origin 값에 optional chaining 적용](https://github.com/boostcampwm2023/web10-Lesser/commit/b298109313d6072d4c366ffb1f2f639583185e79)
- 프론트엔드 개발환경의 편의를 위해 localhost에서 개발할 때 깃허브 인증시 localhost로 리다이렉트되도록 설정
- 로컬 환경에서 깃허브 인증시 `localhost:5173/auth/github/callback` 로 리다이렉트한다.
- 원격 환경에서 깃허브 인증시 `dev.lesser-project.site/auth/github/callback` 로 리다이렉트한다.
- same-site 요청은 request.headers.origin 값이 undefined이므로, includes 메서드에서 오류가 발생하지 않도록 optional chaining 적용
```ts
@Get('github/authorization-server') …
```
=> feat: 로컬 환경에서 깃허브 인증시 localhost 환경으로 리다이렉트 되도록 설정

frontend/src/GlobalErrorBoundary.tsx, frontend/src/apis/api/loginAPI.ts, frontend/src/constants/error.ts, frontend/src/constants/path.ts, frontend/src/pages/TempHomepage.tsx, frontend/src/pages/account/SignupPage.tsx, frontend/src/pages/error/NotPermittedPage.tsx
- signup Page에 접근 제한 기능 개발
- github 로그인을 통해서 signup Page에 접근할 경우 tempIdToken을 전달받는다.
- 따라서 tempIdToken을 전달받지 않은 상태로 signup Page를 접근할 경우, 에러를 던지는 코드를 작성
- 이를 통해 외부 url을 통한 사이트 접근을 제한
- temp page에 가짜 tempIdToken을 전달하는 버튼의 경우 정상적으로 signup page에 접근이 가능
- 하지만, 일반적인 외부 방식으로 signup Page에 접근할 경우, "정상적이지 않은 접근입니다"의 에러 화면을 띄워줌
- logout시 localStorage에 들어있는 모든 데이터를 삭제
=> feat : 외부 signup 페이지 접근 제한 코드 작성

frontend/src/AppRouter.tsx, frontend/src/apis/api/loginAPI.ts, frontend/src/apis/utils/authAPI.ts, frontend/src/components/common/route/PrivateRoute.tsx, frontend/src/components/common/route/PublicRoute.tsx, frontend/src/utils/route/checkAuthentication.ts
- PrivateRouter, PublicRouter를 적용하는 함수의 개선
- 헷갈리게 사용한 isLoading 변수명을 loadingState로 변경
- 기존의 PrivateRouter, PublicRouter를 사용하기 위해선 적용되는 페이지를 모두 Router 혹은 기존에 만들었던 Router 함수로 감싸야 했습니다. 이러한 형태의 코드는 읽기 어려울 뿐만 아니라, 작성하고 유지보수하는데에도 많은 수고를 들이게 했습니다.
- 따라서, PrivateRouter 및 PublicRouter를 한번에 적용하는 형태의 코드를 개발하여, PrivateRouter 혹은 PublicRouter를 적용해야 하는 페이지를 함수안에 모아서 호출하여 사용할 수 있도록 코드를 개선했습니다.
```typescript
// PublicRoute 검사가 필요한 페이지는 이 함수의 파라미터로 전달
...createAuthCheckRouter("PUBLIC", [
{
path: ROUTER_URL.LOGIN,
element: <LoginPage />,
},
{
path: ROUTER_URL.SIGNUP,
element: <SignupPage />,
},
{
path: `${ROUTER_URL.AUTH}/*`,
element: <AuthPage />,
},
]),
// PrivateRoute 검사가 필요한 페이지는 이 함수의 파라미터로 전달
...createAuthCheckRouter("PRIVATE", [
{
path: ROUTER_URL.PROJECTS,
element: <ProjectsPage />,
},
]),
```
=> feat : PublicRouter, PrivateRouter 함수 개선

backend/src/app.module.ts, backend/src/auth/controller/auth.controller.ts, backend/src/auth/service/auth.service.ts, backend/src/common/exception-filter/exception.filter.ts, backend/src/lesser-jwt/lesser-jwt.service.spec.ts, backend/src/lesser-jwt/lesser-jwt.service.ts, backend/src/member/controller/member.controller.ts, backend/src/project/project.controller.ts, backend/test/auth/github-authentication.e2e-spec.ts, backend/test/auth/github-signup.e2e-spec.ts
[백엔드 예외처리 필터 만들기](https://plastic-toad-cb0.notion.site/cfa3e5bdaf4a4f8a851238c58fe84f45)
- [예외처리 필터 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/6dd2615beccf8a605edb125fec3239a6965df482)
- [JWT 검증에서 에러 발생시 어떤 토큰인지 알 수 있도록 토큰 타입을 에러 메시지에 명시](https://github.com/boostcampwm2023/web10-Lesser/commit/21a02d1e9b7cda9c9980792557a41bc136fb25b4)
- [깃허브 외부 API에서 발생하는 에러를 처리할 수 있도록 catch문 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/75a295138a339f1f691c3a4643f8a46f1dd16f4a)
- [e2e 테스트 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/c9b53d6e75b4c2780a7747b3a82b6fa15e32936c)
- [컨트롤러에서 반복되는 에러처리 로직 제거](https://github.com/boostcampwm2023/web10-Lesser/commit/603e954dedc48941e36e6ff597ff3e502cf0a888)
- [JWT 토큰 발행시간(iat)을 ms 단위로 …
=> feat: 예외처리 필터 구현 및 컨트롤러 리팩토링

backend/src/app.module.ts, backend/src/member/entity/member.entity.ts, backend/src/project/dto/CreateProjectRequest.dto.ts, backend/src/project/entity/project-member.entity.ts, backend/src/project/entity/project.entity.ts, backend/src/project/project.controller.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/test/project/create-project.e2e-spec.ts
[프로젝트 생성 API 구현](https://plastic-toad-cb0.notion.site/API-e40c5b055ddb4806bb4b25725dcd5a04?pvs=74)
- [Project 엔티티 생성 및 Member 엔티티와 다대다 관계 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/37b7f59193c06443c49bd2708d07e640a07d5721)
- [ProjectRepository 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/490483ba87ed00d93ec3600253c9af45ab945aa3)
- [프로젝트 생성하는 서비스 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/678282c24e2b1b8a3411e56fb311a0df174a9c70)
- [프로젝트 생성 API 컨트롤러 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/1521b48cd7be5e65f33fed27665f5de04a1351e6)
- [프로젝트 생성 API e2e 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/4e4182a152600df6391e8397f340603db8beeca0)
- Project, Member 엔티티를 ProjectToMember 엔티티에 각각 OneToMany 관계로 연결하여 다대다 …
=> feat: 프로젝트 생성 API 구현

backend/src/project/project.controller.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/test/project/get-project.e2e-spec.ts
[회원의 프로젝트 목록 조회 API 구현](https://plastic-toad-cb0.notion.site/API-0077d972a530456994457f3a2681906a)
- 기존의 더미데이터를 반환하는 프로젝트 목록 조회 API를 실제 데이터를 반환하도록 구현했습니다.
- [회원의 프로젝트 목록을 조회하는 서비스 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/0ef0dac75617c466c6f151ef7a4e32794e3863ae)
- [회원의 프로젝트 목록 조회 API 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/a049270bcefecfa3a4dddfff15386c93a83e91f9)
- member로 프로젝트 목록을 조회하는 레포지토리 메소드 구현 
- [개발일지: TypeORM find 메서드 옵션(select, relations, where)](https://plastic-toad-cb0.notion.site/TypeORM-find-select-relations-where-d89278be2b4b44188e8b5e616f321ebc?pvs=74)
- 서비스 로직에 대한 단위 테스트 작성
- 컨트롤러 로직 구현
- e2e 테스트 작성
=> feat: 회원의 프로젝트 목록 조회 API 구현

backend/src/project/websocket.gateway.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts
[웹소켓 API 구현(백엔드)](https://plastic-toad-cb0.notion.site/API-bebd05a66bca4d35b5b4b15b3ddba8ed?pvs=74)
- fix: socket.io path추가
-  클라이언트 초기연결시 /api/socket.io로 연결하도록 path 설정
- 클라이언트와 실제로 연결해보니 path를 지정하지 않은 부분과 백엔드 Nginx 설정이 `/api` 로 와만 백엔드 로직에서 처리하는 부분이 맞물려 잘 동작하지 않았습니다.
- 이러한 문제를 해결한 방법을 [Socket.io 웹소켓 연결 path 설정](https://plastic-toad-cb0.notion.site/Socket-io-path-b2becebf166442f1b10af36000dfe5c4?pvs=4)에 작성했습니다.
- 웹소켓 E2E 테스트를 도입한 내용을 [웹소켓 E2E 테스트 도입](https://plastic-toad-cb0.notion.site/E2E-d876323ae5974e9abddc108e98e9b551?pvs=4)에 작성했습니다.
=> fix: socket.io path추가

frontend/src/components/account/NicknameInput.tsx, frontend/src/components/account/PositionInput.tsx, frontend/src/components/account/SignupMainSection.tsx, frontend/src/components/account/TechStackInput.tsx, frontend/src/components/common/CategoryButton.tsx, frontend/src/components/common/NextStepButton.tsx, frontend/src/components/landing/LandingProject.tsx, frontend/src/components/projects/ProjectCreateInput.tsx, frontend/src/components/projects/ProjectCreateMainSection.tsx, frontend/src/components/projects/ProjectsSideBar.tsx, frontend/src/constants/projects.ts, frontend/src/pages/account/SignupPage.tsx, frontend/src/pages/projects/ProjectCreatePage.tsx
- [프로젝트 생성 페이지, 회원가입 페이지 UI 개선](https://plastic-toad-cb0.notion.site/UI-f32b836279ae42bfb165f1834d27ca84)
- [프로젝트 버그 픽스](https://plastic-toad-cb0.notion.site/3f73d21dd8f1455092f1d4520b74ceae)
- [회원가입 페이지 버그 픽스](https://plastic-toad-cb0.notion.site/8f13f2a40dd5430892d0729eb88b205d)
- 프로젝트 생성 페이지 및 회원 가입 페이지가 다른 뷰포트에서 일정한 크기로 보일 수 있도록 함
- 프로젝트 목록 페이지 유저 정보 칸 색상을 프로젝트 테마 색으로 변경
- 프로젝트 생성 페이지에서 제목 입력 후 엔터를 쳤을 때 바로 프로젝트가 생성되는 버그 해결
- 프로젝트 페이지에서 프로젝트 데이터가 오기 전에 프로젝트 생성 날짜가 NaN.NaN.NaN으로 보이는 문제 해결
- 회원 가입 페이지에서 닉네임 입력값을 다 지웠는데 중복검사 API 요청되는 버그 해결
[개발일지](https://plastic-toad-cb0.notion.site/ca1f9f0aee034760b26d543c502acedd?pvs=74)
- 한글 입력 시 IME로 인해 `keyDown` 이벤트가 두 번 감지되어 발생하는 버그였습니다. Mac에서는 `composition` 중에 감지되는 `keyDown` 이벤트에서 받는 key의 값이 `Enter`로 되어 있어서 발생했습니다. 따라서 `composition`중이 아닐 때만 enter …
=> fix: 프로젝트 생성, 회원 가입 페이지 버그 해결, 데모 피드백 반영

backend/src/app.controller.ts, backend/src/app.module.ts, backend/src/auth/controller/auth.controller.ts, backend/src/common/guard/authentication.guard.ts, backend/src/member/controller/member.controller.ts, backend/src/member/member.module.ts, backend/src/project/project.controller.ts, backend/test/project/create-project.e2e-spec.ts
[가드 구현](https://plastic-toad-cb0.notion.site/80019425274d475b8d977128566cfe1f?pvs=4)
ex)
- 인증역할을 하는 AuthenticationGuard 구현
- 전역가드 설정, 공개경로 public 데코레이터 추가
- 컨트롤러 핸들러에 진입하기 전 인증을 수행하고 request객체에 member 정보를 수행하는 AuthenticationGuard 구현
- project 컨트롤러의 인증로직을 삭제하고 가드를 적용
- 프로젝트 생성의 body 데이터 형식 검사하는 테스트(400)에서 인증 여부가 영향을 주지 않도록 유효한 엑세스토큰을 추가해 테스트하도록 변경
- app module에 전역가드 설정
- public 커스텀 데코레이터 추가
- public 데코레이터가 설정된 경로에 대해 인증절차 건너뛰도록 가드 변경
- authController등 인증 없는 경로에 대해 public 데코레이터 적용
- 가드의 도입 이유는 반복되는 인증절차를 가드라는 공통적인 계층으로 추상화해 처리하기 위함입니다.
- 미래에 대부분의 API에서 인증을 필수로 처리할 것으로 예상되어 전역가드로 처리했습니다.
- 인증이 필요하지 않은 경로는 @Public() 데코레이터를 붙여 인증에서 제외할 수 있습니다.
- 컨트롤러에서 사용하는 `request`와 bearerToken 정보를 추가한 `BearerTokenRequest`를 확장해 인증정보를 추가한 `MemberRequest`인터페이스를 추가했습니다.
- 400테스트에 유효한 엑세스토큰을 넣어주도록 수정했습니다.
- …
=> refactor: 인증을 처리하는 가드계층 추가

backend/src/project/entity/project.entity.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts
[랜딩페이지 API 추가구현(초대링크)](https://plastic-toad-cb0.notion.site/API-e6cf4e115ac7443e90e89d0a81327f8b)
- project 엔티티에 프로젝트 생성시 uuid가 자동으로 생성되는 inviteLinkId 필드 추가
- 웹소켓 게이트웨이에 joinLanding 이벤트의 첫 데이터 전송으로 inviteLinkId 프로퍼티 추가 전송
- 웹소켓 랜딩페이지 inviteLinkId에 대해 e2e 테스트 추가
- mysql에서는 column의 type으로 uuid를 사용하는게 불가능하다고 하네요
- https://orkhan.gitbook.io/typeorm/docs/entities#column-types-for-mysql-mariadb 
- 그래도 명시적으로 uuid로 해 놓으면 보기 편할것 같습니다. 
- mysql에 varchar로 들어가는것을 확인했습니다.
```bash
mysql> desc project;
+------------+--------------+------+-----+----------------------+--------------------------------------------------+
| Field      | Type         | Null | Key | Default              | Extra                                            |
+------------+--------------+------+-----+----------------------+-------- …
```
=> feat: 프로젝트 초대링크 API 구현

backend/src/project/dto/JoinProjectRequest.dto.ts, backend/src/project/project.controller.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/test/project/join-project.e2e-spec.ts, backend/test/setup.ts
[프로젝트 회원추가 API 구현](https://plastic-toad-cb0.notion.site/API-e62f4ab25adc47aab594711d09bc233c?pvs=74)
- feat: project 레포지토리에서 getProjectLinkId, getProjectToMember 메서드 구현
- feat: 프로젝트 서비스에 멤버추가 메서드 구현
- feat: 프로젝트 컨트롤러에 프로젝트 참여 엔드포인트 구현
- test: join project E2E 테스트 구현
- getProjectLinkId는 프로젝트의 초대링크 아이디로 프로젝트를 찾는 메서드임
- getProjectToMember는 멤버와 프로젝트의 정보를 받아 멤버가 프로젝트에 참여한 경우 ProjectToMember 정보를 반환하는 메서드임
- addMember 메서드는 프로젝트 링크를 받아 프로젝트에 회원을 추가한다.
- isProjectMember는 회원이 프로젝트의 회원인지 확인한다.
- getProjectByLinkId는 프로젝트 링크로 프로젝트를 찾는다.
- joinProject로 회원이 프로젝트 링크로 프로젝트에 참여할 수 있도록 한다.
- JoinProjectRequestDto로 '/join' 엔드포인트의 요청형식을 검증한다.
- 회원이 정상적으로 프로젝트에 참여할때 201 반환 테스트
- 회원이 이미 프로젝트에 참여한 경우 200 반환 테스트
- 토큰이 유효하지 않을경우 401 반환 테스트
- body의 형식이 유효하지 않을 경우 400 반환 테스트
- 프로젝트 링크가 유효하지 않을 경우 404 반환 테스트
- 이미 …
=> feat: 프로젝트 참여 API 구현

backend/src/project/project.controller.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts
[프로젝트 addMember 서비스의 매개변수를 projectLinkId → project로 변경](https://plastic-toad-cb0.notion.site/addMember-projectLinkId-project-3fb96fa0838d4071aeac2b712d25a432)
- [프로젝트 addMember 서비스의 매개변수를 projectLinkId → project로 변경](https://github.com/boostcampwm2023/web10-Lesser/commit/ed7b77e7370c208660569430d20549ceb7afc640)
- addMember 서비스 로직의 재사용성을 고려해 기존에 uuid인 projectLinkId를 매개변수로 받던 부분을 Project 객체를 받도록 변경하였습니다. 
- 이에 따라 addMember 서비스 로직에서 getProjectByLinkId를 호출하던 부분을 삭제했고, 
- 단위 테스트 및 컨트롤러 addMember 호출자를 수정했습니다.
```ts
async addMember(project: Project, member: Member): Promise<void> {
const isProjectMember = await this.isProjectMember(project, member);
if (isProjectMember) throw new Error('already joined member');
await this.projectRepository.addProjectMember(project, member);
}
```
=> refactor: 프로젝트 addMember 서비스의 매개변수를 projectLinkId → project로 변경

frontend/src/AppRouter.tsx, frontend/src/apis/api/loginAPI.ts, frontend/src/apis/api/projectAPI.ts, frontend/src/components/account/SignupMainSection.tsx, frontend/src/components/common/route/PublicRoute.tsx, frontend/src/components/landing/LandingMember.tsx, frontend/src/constants/path.ts, frontend/src/constants/storageKey.ts, frontend/src/hooks/common/socket/useLandingSocket.ts, frontend/src/pages/TempHomepage.tsx, frontend/src/pages/invite/InvitePage.tsx, frontend/src/pages/landing/LandingPage.tsx, frontend/src/types/DTO/landingDTO.ts
- [프로젝트 참여 신청 페이지 UI(디자인 x 기본 기능만 있는 UI)](https://plastic-toad-cb0.notion.site/UI-x-UI-5bb0bc27ea58414b858e45f9b5663a84)
- [프론트 리다이렉트 로직 작성](https://plastic-toad-cb0.notion.site/3d6ab350e8f2431c9674ed3e4218336b)
- [클라이언트 멤버 추가 API 연결 로직 작성 및 연결 확인](https://plastic-toad-cb0.notion.site/API-72f4d62ea1754b2d988c93729a1af750)
- 시나리오에 맞는 클라이언트 리다이렉트 로직 작성
- 임시 초대 페이지 생성 및 라우터 연결
- 프로젝트 참가 API 연결
- 리다이렉트 로직을 작성할 때 두 가지 방법을 고민했습니다. 하나는 url의 쿼리스트링으로 redirectURL을 관리하는 것이고 하나는 sessionStorage에 관리하는 것입니다. 쿼리스트링으로 관리하려면 OAuth를 사용하기에 github로 redirectURL 정보를 담아 요청을 보내고 다시 받아올 수 있어야 합니다. 찾아본 결과 state라는 파라미터를 인증 절차 이후에 접근하고 싶은 클라이언트의 상태를 보내는 데 사용한다는 정보를 발견했습니다. 하지만 문자열 그대로 보내는 것은 보안상 안전하지 않아 암호화해야 하는데, 그러려면 클라이언트에서 암호화 키를 저장해두어야 하며 리다이렉트 되는 동안 기억하려면 브라우저 Storage에 저장해야 한다고 판단했습니다. 그런데 어차피 Storage를 사용할 것이라면 …
=> feat: 임시 초대 페이지 생성 및 참가 API 연결

backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/join-project.e2e-spec.ts, backend/test/project/ws-connection.e2e-spec.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts, backend/test/setup.ts
[socket.io API 인증, 인가 (백엔드)](https://plastic-toad-cb0.notion.site/socket-io-API-6e2999b629c54253a5fe27a5f93ed9e0?pvs=74)
- feat: 웹소켓 인증, 인가 구현
- test: 클라이언트 socket io 연결시의 성공, 실패 테스트 구현
- refector: setup 모듈을 이용한 테스트 중복제거
- 웹소켓 게이트웨이에 afterInit을 추가해 클라이언트가 핸드쉐이크시 인증, 인가 성공시에 연결되도록 구현
- 가드를 재활용하기 어려줘 게이트웨이 내부에 authentcation, authorization 함수 추가
- socket io 연결 성공시 connect 이벤트 확인
- token 없이 핸드쉐이크시 connect_error 확인
- 유효하지 않은 token으로 핸드쉐이크시 connect_error 확인
- 존재하지 않는 프로젝트로 연결시 connect_error 확인
- 유효하지 않은 형식의 프로젝트Id로 연결시 connect_error 확인
- 내가 참여하지 않은 프로젝트로 연결시 connect_error 확인
- 테스트 실패시 최대한 타임아웃이 안나도록 connect/connect_error시 reject하도록 변경
- setup 모듈에 createProject 구현
- setup 모듈에 projectPayload 추가
- setup 모듈에 서버 소켓과 연결하는 connectServer 구현
- projectPayload setup모듈의 객체 사용
- setup모듈의 export인 …
=> feat: 서버 socket.io 인증, 인가 구현

frontend/src/AppRouter.tsx, frontend/src/apis/utils/authAPI.ts, frontend/src/hooks/common/socket/useSocket.ts
[클라이언트에서 웹소켓 연결시 액세스 토큰 보내기](https://www.notion.so/95e0d5fe9d814f58ab8f9b215aeed7a5?pvs=4)
- 웹소켓에서 엑세스토큰을 담아 전달하도록 코드 수정
- main page를 private router로 이동
accessToken을 socket.io에 전달하여 웹소켓 통신 생성
1. accessToken을 가지고 오는 getAccessToken 함수 작성
- 함수 형태로 가져오는 코드 작성 : accessToken을 가지고 오면서 추가적인 처리가 있을 수 있기 때문에 함수로 처리
2. io함수에 auth 설정 추가
- main page의 경우, 새로고침 혹은 accessToken 만료의 경우 새롭게 데이터를 받아오지 못하는 문제 발생
- private router에 main page를 배치하여 accessToken을 검증하며 refresh하는 코드 동작
=> feat : 클라이언트에서 웹소켓 연결시 액세스 토큰 보내기

backend/src/auth/service/auth.service.ts, backend/src/member/entity/member.entity.ts, backend/src/member/service/member.service.ts, backend/test/auth/get-github-username.e2e-spec.ts, backend/test/auth/github-signup.e2e-spec.ts, backend/test/project/join-project.e2e-spec.ts, backend/test/project/ws-connection.e2e-spec.ts, backend/test/setup.ts
[E2E 테스트 멤버, 프로젝트 등 Fixture 데이터베이스에 저장하는 메서드 만들기 (JoinProject)](https://plastic-toad-cb0.notion.site/E2E-Fixture-JoinProject-bf75bb5dfff2456b9854bd5130e55d1f?pvs=74)
- refector: setup에서 기본적으로 이루어지는 깃허브 모킹로직 삭제, createMember 메서드 내부에서 모킹을 하도록 변경
- refector: Member 엔티티의 techStack 프로퍼티 타입 변경
- refector: setup 모듈에서 프로젝트의 링크아이디 얻는 메서드, 프로젝트에 참여하는 메서드 추가
올바른 타입 추론을 위해 Member 엔티티의 techStack 프로퍼티 타입을 `object`에서 `stacks: string[]`으로 변경
- setup에서 기본적으로 이루어지는 깃허브 모킹로직 삭제
- setup 단계의 로직을 이해하고 있지 않으면, 테스트로직만 보고 이해할 수 없기 때문에 setup의 모킹 로직 삭제
- createMember 메서드 내부에서 모킹을 하도록 변경
- 기존의 로직은 모킹을 한 후, createMember를 호출해야 정상적인 처리가 가능했음. 이 사실을 몰라도 createMember를 사용할 수 있도록 변경
- createMember의 매개변수를 Member타입으로 지정
- memberFixture를 member 타입으로 변경
- setup 모듈에서 프로젝트의 링크아이디 얻는 메서드
- 프로젝트에 참여하는 메서드 추가
- E2E 테스트에서 …
=> refector: 테스트 셋업 메서드 추가

backend/src/app.module.ts, backend/src/member/service/member.service.spec.ts, backend/src/member/service/member.service.ts, backend/src/project/dto/MemoCreateRequest.dto.ts, backend/src/project/entity/memo.entity.ts, backend/src/project/entity/project.entity.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-memo.e2e-spec.ts, backend/test/setup.ts
[메모 생성 웹소켓 API 구현 (백)](https://plastic-toad-cb0.notion.site/API-28e767d42bf247bf8d3b8950f30aa313?pvs=74)
- 메모 생성 API e2e 테스트코드 추가
- 메모 엔티티 생성
- 메모생성 서비스 구현
- 메모 생성 게이트웨이 구현
- 회원 2명이 랜딩 페이지에 접속한 상태에서 메모 생성시 모든 회원이 생성된 메모 데이터를 받는 테스트 추가
- 잘못된 메모 데이터 전송시 에러 수신하는 테스트 추가
- 메모 엔티티 생성
- 프로젝트 엔티티에 메모 프로퍼티 추가
- 모듈에 메모 등록
- project 레포지토리, 서비스에 메모를 생성하는 createMemo 메서드 구현
- 메모생성 유닛 테스트 추가
- member 서비스에 회원을 id로 조회하는 getMember 메서드 구현
- 회원조회 유닛 테스트 추가
- 'memo' 이벤트를 구독하는 게이트웨이 구현
- 데이터 형식 검증로직 구현
- memoCreateRequest DTO 추가
- 메모 생성시 'landing' 페이지에 접속한 회원에게 이벤트를 전송하는 로직 구현
- 웹소켓 테스트에서 여러명의 클라이언트가 서버에 연결하는 로직을 작성해야 했습니다. 이때 모두가 방에 참여한 상태에서 메모를 생성하고 
적절한 데이터를 받는것을 테스트해야 했는데, socket.io API는 콜백함수를 받는 이벤트 형식으로 되어있어서 여러명의 클라이언트가 모두 방에 참여한 것을 보장하는 로직을 작성하면 콜백지옥에 빠지게 되었습니다.
```ts
socket1.on("connect", () => { …
```
=> feat: 메모 생성 API 구현

backend/src/project/dto/MemoCreateRequest.dto.ts, backend/src/project/entity/memo.entity.ts, backend/test/project/ws-memo.e2e-spec.ts
- 같은 회원이 여러개의 메모를 생성할 수 없는 버그 수정
- 메모와 회원이 one to one으로 연결되어 있어서 메모의 member_id 컬럼에 unique제약조건이 붙음
- many to one으로 수정함
- 회귀 테스트 추가
- 메모 생성 API에서 content속성을 보내지 않으면 internal error가 반환되는 버그 수정
- ClassValidator의 ValidateNested 데코레이터를 사용하고, 검사하고자 하는 객체가 undefined일때 validate를 통과하는 이슈가 있음
- isNotEmpty 데코레이터를 추가해 해결함
- 회귀 테스트 추가
- 한명의 회원이 여러번 메모를 생성시 아래와 같은 에러가 나왔습니다.
- 메모 테이블과 회원 테이블이 OneToOne으로 연결되어있었고 이는 의도하지 않은 구현이었습니다.
```
@OneToOne(() => Member, (member) => member.id, { nullable: false })
@JoinColumn({ name: 'member_id' })
member: Member;
```
- 그리고 에러가 생긴 원인은 테이블이 OneToOne으로 연결되어있으면 unique 제약조건을 걸어서 생기는 문제였습니다.
- 이를 ManyToOne관계로 변경해 해결했습니다.
- 클라이언트가 메모 생성 API에서 content속성을 보내지 않았을때 저희가 정의한 error이벤트를 받는것을 기대했지만 Nest가 보내주는 Exception 이벤트가 오는것을 확인했습니다.
- 기존의 DTO는 아래의 코드였습니다.
```
class Color { …
```
=> fix: 메모 생성 API 버그수정 및 회귀 테스트 추가

backend/src/project/dto/MemoDeleteRequest.dto.ts, backend/src/project/entity/memo.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-memo.e2e-spec.ts
[메모 삭제 웹소켓 API 구현 (백)](https://plastic-toad-cb0.notion.site/API-b3cf77a7f9f343aebdb5f518f7dbd022?pvs=74)
- [test: 메모 삭제 API e2e 테스트 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/f6ea656559d6bd8705582ca87dc39508343f2e93)
- [feat: 메모를 삭제하는 레포지토리 메서드 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/accf1b0895e17c4edf2212869cb351dec3ef5a68)
- [feat: 메모 삭제 서비스 로직 및 단위테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/054f24ffd5c33061df6d3cc392beaf6501be9a35)
- [feat: 메모 삭제 웹소켓 API 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/1ad72dca56884e2857fd1285a882496ec52ddec4)
- 회원 2명이 랜딩 페이지에 접속한 상태에서 메모 삭제시 모든 회원이 삭제된 메모 id를 이벤트로 받는 테스트 추가
- 잘못된 데이터 형식 전송시 에러 수신하는 테스트 추가
- 삭제된 레코드 개수를 반환한다. 삭제된 레코드가 없으면 0을 반환한다.
- deleteMemo 서비스는 삭제 여부를 boolean 값으로 반환
- …
=> feat: 메모 삭제 웹소켓 API 구현

backend/src/project/dto/InitLandingResponse.dto.ts, backend/src/project/entity/memo.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts
[랜딩페이지 API 메모정보 추가 구현 (백)](https://plastic-toad-cb0.notion.site/API-6203dd08d98e436dbad0bedfacb9774f?pvs=74)
- 랜딩페이지 접속 API 프로젝트의 메모 테스트 추가
- 프로젝트의 메모를 조회하는 레포지토리 메서드 구현
- 프로젝트의 메모를 조회하는 서비스로직 구현
- 랜딩페이지 접속 API에서 프로젝트의 메모정보 반환하도록 구현
- 메모를 생성한 후, 랜딩페이지에 접속했을때 생성한 메모를 받는지 확인하는 테스트 추가
- 프로젝트의 메모를 생성한 회원의 정보와 조인해 반환하는 메서드 구현
- 메모의 프로젝트 Id를 조인없이 접근할 수 있도록 projectId 프로퍼티 추가
- 프로젝트의 메모를 작성자 정보와 함께 반환하는 서비스 구현
- 서비스 테스트 추가
- 게이트웨이에서 랜딩페이지 접속일때 메모정보를 추가적으로 반환하도록 구현
- 게이트웨이의 복잡한 반환 메시지를 만드는 로직을 InitLandingResponseDto를 만들어 of 메서드로 추상화
=> feat: 랜딩페이지 접속 API에 메모 정보 추가구현

backend/src/project/dto/MemoColorUpdateRequest.dto.ts, backend/src/project/entity/memo.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-memo.e2e-spec.ts
[메모 색상 변경 웹소켓 API 구현 (백)](https://plastic-toad-cb0.notion.site/API-864bee8ab8824fa79cc6301d881ef8fc)
- 메모 색상 업데이트 e2e 테스트 작성
- 프로젝트의 메모조회, 메모 색상 업데이트 레포티토리 메서드 구현
- 메모색상 업데이트 서비스 구현
- 메모색상 업데이트 컨트롤러 구현
- 모든 테스트의 가장 바깥 describe에 'WS memo' describe 추가
- 각 테스트의 인덴트 변경
- 메모 색상변경 API 테스트 추가
- 성공상황 테스트
- 데이터 형식 오류로 인한 실패상황 테스트
- 프로젝트의 메모조회, 메모 색상 업데이트 레포티토리 메서드 구현
- 메모 엔티티의 projectId의 타입을 int로 명시
- 메모가 존재하고 해당 프로젝트의 메모일때 메모 색상을 업데이트 하고 true 반환
- 메모가 존재하지 않을때 false 반환
- 메모가 해당 프로젝트의 메모가 아닐때 throw
- 이에대한 테스트와 구현 작성
- 요청검증을 위한 requestDto 작성
- 메모 색성 업데이트 컨트롤러 로직 구현
- 접근하고자 하는 메모가 해당 프로젝트의 메모가 아닌 경우에 대해 서비스는 throw를 하는 방식으로 처리했습니다. 컨트롤러에서 이를 무시하고 있게 구현했는데 이를 클라이언트에게 보내줄건지 논의하면 좋을것같습니다.
- 현재 메모삭제의 경우 메모가 해당 프로젝트의 메모인지 확인하지 않고있습니다. 확인하는 로직을 추후에 추가해야 할 것 같습니다.
=> feat: 메모 색상 변경 API 구현

frontend/src/components/landing/memo/LandingMemoList.tsx, frontend/src/components/landing/memo/MemoBlock.tsx, frontend/src/components/landing/memo/MemoColorButton.tsx, frontend/src/components/landing/memo/MemoEditor.tsx, frontend/src/hooks/common/socket/useLandingEmitEvent.ts, frontend/src/hooks/common/socket/useLandingSocket.ts, frontend/src/pages/landing/LandingPage.tsx, frontend/src/types/common/landing.ts
[웹소켓 메모 생성 이벤트 처리 로직 작성 (프론트)](https://www.notion.so/30bb88503ecd4281b0c79e843e106185?pvs=4)
[웹소켓 메모 삭제 이벤트 처리 로직 작성 (프론트)](https://www.notion.so/65a474cc64e641178d09da0b9f1c6962?pvs=4)
- Memo 삭제 / 생성 / 색상 변경 소켓 통신 데이터를 규격에 맞추어 전달하는 코드 생성
- 서버로부터 전달 받는 Memo 삭제 / 생성 신호에 맞추어 memoList 상태값을 새롭게 갱신하는 형태로 데이터 수정
- 메모 색상 변경의 경우, 서버의 api 작업이 완료되면 새로운 PR로 올릴 예정 
- useLandingSocket 내 landing 이벤트 핸들링 함수의 리팩토링
- useLandingEmitEvent 커스텀 훅을 생성
- 사용자가 특정 행동(요소 생성 / 삭제 / 수정)을 취할 경우, 해당 내역을 서버에 전달해야 합니다. 이를 위해, Socket.io를 통해 생성한 Socket 객체를 통해 정해진 신호를 전달하는 함수를 생성하여 전달하는 커스텀 훅 useLandingEmitEvent를 만들어 Landing페이지의 모든 이벤트를 관리할 수 있도록 만들었습니다.
- useLandingEmitEvent를 통해 만들어진 "신호 전달 함수"를 각 요소에 전달
- useLandingEmitEvent를 통해 만들어진 메모 생성/수정/삭제 함수를 각 버튼 요소에 전달할 수 있도록 각 요소를 prop을 통해 전달하는 구조로 설계했습니다.
- useLandingSocket 내 …
=> feat : 메모 생성 및 삭제 기능 완성

frontend/src/components/account/NicknameInput.tsx, frontend/src/components/account/PositionInput.tsx, frontend/src/components/account/SignupMainSection.tsx, frontend/src/components/account/TechStackInput.tsx, frontend/src/components/account/TechStackModal.tsx, frontend/src/hooks/common/dropdown/useDropdown.tsx, frontend/src/hooks/pages/account/useWheelDown.ts, frontend/src/hooks/pages/account/useWheelUp.ts
[회원가입 스크롤 단계 이동 동작 구현](https://www.notion.so/94101d27f4c14b5c946423a0734de330?pvs=21)
- 스크롤을 통한 단계 이동 기능 구현
- SignupPage 리팩토링
- 스크롤을 이동하면 다음 단계로 이동하는 것이기에 처음에는 스크롤 이벤트를 통해 구현하려고 했습니다. 그런데 overflow-hidden이 된 상태에서는 스크롤 이벤트를 감지할 수 없어서 다른 방법을 찾아야 했습니다. 그래서 알게 된 것이 wheel 이벤트였습니다. wheel 이벤트는 마우스 휠과 관련된 이벤트이며, 휠을 아래로 움직이면 deltaY의 값이 양수로, 위로 움직이면 양수로 나타납니다. 따라서 이를 이용해 기능을 구현했습니다.
- 기존에 document.getElementById를 통해 엘리먼트를 특정하고 scroll 이벤트를 발생시키던 것을 Ref를 요소에 연결하고 이를 이용하는 것으로 변경했습니다. 리액트 공식문서에서 ref를 이러한 용도로 사용하는 것이 예시로 나와 있으며, 해당 기능 구현에 순수 자바스크립트를 이용할 필요가 없다고 판단했기 때문에 수정했습니다.
- 브라우저 창이 줄어들면 가로 및 세로 스크롤바가 나타나는데, 이로 인해 wheel 이벤트 관련 로직이 제대로 동작하지 않는 경우가 있었습니다. 스크롤바를 없애지 않는 선에서 여러 방식으로 이를 해결하려 시도해봤지만 완벽한 방법은 없었습니다. 그래서 우선 회원가입 페이지에서 세로 스크롤바가 생기지 않도록 hidden 설정을 주었는데(저희 서비스는 모바일은 고려하지 않고 있고, 대부분의 경우 세로 스크롤바가 …
=> feat: 회원가입 페이지에서 마우스 휠로 단계를 넘어가는 기능

backend/src/project/dto/InitLandingResponse.dto.ts, backend/src/project/dto/MemberUpdateRequest.dto.ts, backend/src/project/enum/MemberStatus.enum.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-common.ts, backend/test/project/ws-memo.e2e-spec.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts, backend/test/project/ws-update-member-status.e2e-spec.ts
[서버에서 프로젝트 구성원 상태 변경을 웹소켓으로 받고 전체 구성원에게 브로드캐스팅하는 API 구현 (백엔드)](https://plastic-toad-cb0.notion.site/API-647eaafb68d043f4b6a0dc92e5029e83?pvs=74)
- 프로젝트의 회원목록을 조회하는 레포지토리 메서드 구현
- 프로젝트의 회원목록을 조회하는 서비스 메서드 구현
- 회원상태 업데이트 API 구현
- 웹소켓 테스트에서 공통적으로 사용하는 메서드 분리
- 랜딩페이지 접속시 자신의 정보를 조회하는 테스트 추가
- 웹소켓 메모 테스트 수정
- 회원의 상태 변경 테스트 추가
- 프로젝트의 목록 조회 서비스 메서드에 대한 테스트 구현
- 프로젝트의 목록 조회 서비스 메서드 구현
- 회원의 status를 Enum파일로 분리
- 랜딩페이지 접속시 회원관련 정보를 조회할 수 있게 구현
- 회원의 상태 업데이트에 대해 RequestDto 추가
- 회원상태 업데이트 API 컨트롤러 구현
- 회원 접속시 자동으로 회원의 상태를 on으로 변경
- 회원이 업데이트 메시지를 보내면, 회원의 상태를 변경함
- waitStatusMsg는 다른 회원 접속시 상태 변경 메시지를 기다리는 메서드임
- waitLandingAndStatusMsgAndReturnId는 최초 접속시 랜딩페이지 정보와 자신의 상태 변경 메시지를 기다리는 메서드임
- initLanding은 랜딩페이지 조회메시지를 제외하고는 무시하는 메서드임
- 접속시 회원 정보 업데이트를 자동으로 보내는 로직으로 수정되었기 때문에, 기존의 테스트가 실패함.
- 다시 테스트를 …
=> feat: 회원의 상태 변경 API 구현

backend/src/project/websocket.gateway.ts, backend/test/project/ws-common.ts, backend/test/project/ws-memo.e2e-spec.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts, backend/test/project/ws-update-member-status.e2e-spec.ts, backend/test/setup.ts
- fix: 랜딩페이지 접속시 자기자신에게는 회원상태정보를 보내지 않도록 수정
- chore: 테스트에서 공통으로 사용하는 함수를 분리
- 공통으로 사용하는 함수를 분리
- 관심이 없는 메시지를 무시하는 테스트 함수 삭제
- 랜딩페이지 접속시 접속하는 유저가 자신의 상태변경 메시지를 받지 않도록 변경되면서, 복잡하게 순서가 보장되지 않는 메시지를 검증할 필요가 없어, 이 부분을 수정하고 테스트에 반영했습니다.
- 추후 순서가 보장되지 않는 여러개의 메시지를 검증할 필요가 있을때, 이전에 작성해 놓았던 테스트 로직을 활용하면 좋을 것 같습니다.
- 아래와 같이 재귀적으로 확인합니다.
```typescript
export const waitLandingAndStatusMsgAndReturnId = (
socket: Socket,
isInitLandingMsg: boolean,
isUpdateStatusMsg: boolean,
) => {
return new Promise<void>((resolve, reject) => {
socket.on('landing', async (data) => {
socket.off('landing');
const { action, content, domain } = data;
if (action === 'init' && domain === 'landing') {
if (!isUpdateStatusMsg) {
await waitLandingAndStatusMsgAndReturnId(socket, true, false);
}
resolve(content.myInfo.id); …
```
=> chore: 웹소켓 테스트에서 공통으로 사용하는 함수 분리

backend/src/project/project.controller.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-common.ts, backend/test/project/ws-join-project.e2e-spec.ts, backend/test/setup.ts
[프로젝트 가입 API에서 랜딩페이지에 접속해있는 회원에게 프로젝트에 새로 추가된 회원정보 전송](https://plastic-toad-cb0.notion.site/API-e2631eb68ee347f0823265adedd9e914?pvs=74)
- 새로운 회원이 프로젝트 참여시 프로젝트의 랜딩페이지에 접속해 있는 회원에게 회원정보 업데이트 구현
- 프로젝트 참여시 프로젝트에 접속해 있는 회원에게 알리는 테스트 추가
- 웹소켓 게이트웨이에 연결되어 있는 회원에게 새로운 회원이 프로젝트에 참여했음을 알리는 메서드 구현
- 프로젝트 참여 컨트롤러에 웹소켓 게이트웨이 로직 추가
- 프로젝트 참여 웹소켓 테스트 추가
- 테스트에서 웹소켓의 이벤트가 한번만 사용되도록 once로 변경
- dynamic 네임스페이스를 사용하는 경우 `@WebSocketServer()`로 접근할 수 있는 변수는 ParentNamespace 객체입니다. 이는 Namespace가 동적이라 여러개 있기 때문에, 클래스 자체에서 접근하는 변수는 Namespace를 여러개 가지고 있는 ParentNamespace가 되기 때문입니다.
- 그러나 ParentNamespace 타입의 경우 socket.io 라이브러리에서 export하지 않습니다. 따라서 이를 직접 사용하는것은 라이브러리의 의도와는 벗어난다고 생각해 직접 네임스페이스 Map을 만들었고, <프로젝트 이름, 네임스페이스>형태로 네임스페이스에 직접 접근할 수 있게 했습니다.
```
export class ProjectWebsocketGateway implements OnGatewayInit { …
```
=> feat: 프로젝트 참여시 랜딩페이지에 접속한 회원에게 새로운 회원의 정보를 알리는 API 구현

backend/src/project/dto/InitLandingResponse.dto.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts, backend/test/setup.ts
[최초 랜딩페이지 접속시 본인을 포함한 프로젝트 멤버들의 접속 상태 정보를 응답하도록 구현](https://plastic-toad-cb0.notion.site/5f639bb4c8aa4deb9bc34464e66f1e6f?pvs=74)
- [feat: E2E 테스트에서 access token으로 member 객체를 받아오는 메서드 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/fa81b978e4bd6b5833836777bd69c779ff22759b)
- [feat: 최초 랜딩페이지 접속시 본인을 포함한 프로젝트 멤버들의 접속 상태 정보를 응답하도록 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/214b874e506c25ce592b65fa10c0365670b61a8c)
- [test: 랜딩페이지 데이터 중 멤버 접속 상태 정보 관련 E2E 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/f062bd0cdcc30f1b69528209545e8fdc4bfad680)
- E2E 테스트 중 데이터베이스에 저장된 회원의 정보를 용이하게 사용할 수 있도록 추가하였습니다.
- 접속한 본인의 접속 상태 정보(myInfo) 및 프로젝트 멤버들의 접속 상태 정보를 projectSocketList 각각의 소켓에 저장된 접속 상태 정보를 이용해 반환
- fetchSockets() 메서드를 통해 프로젝트 네임스페이스에 연결된 소켓 …
=> feat: 최초 랜딩페이지 접속시 본인을 포함한 프로젝트 멤버들의 접속 상태 정보를 응답하도록 구현

frontend/src/components/landing/memo/MemoBlock.tsx, frontend/src/hooks/common/landing/useLandingMemo.tsx, frontend/src/hooks/common/socket/useLandingSocket.ts
[MemoList 색상변경 코드 리팩토링](https://www.notion.so/MemoList-df8a7eb15e184ff79b606d0b873ac739?pvs=4)
- 메모가 변경되면, 화면에 변경된 색상으로 반영되도록 수정
- 메모 전체 상태값에서 색상이 변경되게 되면, 해당 값을 메모 상태값에서 수정하는 코드 작성
- 기존 코드의 문제점 : 메모 전체 데이터에서 값을 받아 새롭게 메모의 색상 상태값을 만들어 관리
- 따라서, 전체 메모가 변경되더라도 메모의 색상 상태값이 변경되지 않았기 때문에 색상이 변하지 않음
- 메모의 색상 상태값을 별도로 관리해야 할 이유가 없음에도 해당 방식으로 설계한 실수로 인해 작동하지 않음
- 해당 방식을 개선하여, 현재는 메모의 색상이 모든 사용자에게 동시에 변경되도록 설계완료함 
- 각 칸반보드 컴포넌트마다 wrapper를 적용해서 그룹화 했을 때 같은 그룹에 속한 태스크만 옮길 수 있도록 했습니다.
- 선택한 태스크의 배경 색을 변경해 선택되었음을 확실히 인지할 수 있도록 했습니다.
- 태스크 수정 api와 연결해 태스크를 드롭하면 실제 태스크의 상태가 변경될 수 있도록 했습니다.
- api 연결에는 `usePostTaskState`라는 커스텀 훅을 만들어 사용했습니다.
=> refactor : 서버에서 전달하는 데이터를 받아서 화면에 색상을 반영하는 코드 작성

backend/src/project/project.controller.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/test/project/join-project.e2e-spec.ts
[프로젝트의 총 인원을 10명으로 제한하는 로직(백)](https://plastic-toad-cb0.notion.site/10-dd837dc887314cfc81fd90883bc1556f?pvs=74)
- 프로젝트의 인원이 10명 이상일때, 새로운 인원이 참여하지 못하게하는 서비스 로직 구현
- 서비스 테스트 추가
- 서비스의 throw를 catch해 Conflict로 throw하는 컨트롤러 로직 구현
- 10명 이상 참여시 401반환을 테스트하는 E2E 테스트 추가
=> feat: 프로젝트의 인원이 10명 이상일때, 새로운 인원이 참여하지 못하게하는 API 구현

backend/src/project/websocket.gateway.ts, backend/test/project/ws-update-member-status.e2e-spec.ts
[접속 상태 변경 예시 구체화, E2E 테스트 작성](https://plastic-toad-cb0.notion.site/E2E-a5c34f0aba1144abb1617fa42047af8b?pvs=74)
- [접속 상태 변경과 관련한 로직 추가 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/b807fad6eabdc741b1e054bf61142e770281eef4)[접속 상태 변경과 관련한 로직 추가 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/b807fad6eabdc741b1e054bf61142e770281eef4)
- [접속 상태 변경과 관련한 E2E 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/54f69486230f0ed52648da9f7deb345bee0c9ed6)[접속 상태 변경과 관련한 E2E 테스트 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/54f69486230f0ed52648da9f7deb345bee0c9ed6)
- 소켓 disconnect시 네임스페이스에 포함된 다른 소켓들에게 off 상태를 전달하는 로직 구현(handleDisconnect)
- 다만, 같은 회원의 다른 소켓이 연결되어 있는 상태라면 off 상태를 전달하지 않는다.
- 프로젝트 랜딩페이지 조인시(joinLanding) 네임스페이스에 연결된 소켓 중 같은 회원의 소켓이 있는지 확인하고, …
=> feat: 접속 상태 변경과 관련한 로직 추가 구현

backend/src/app.module.ts, backend/src/project/dto/LinkCreateRequest.dto.ts, backend/src/project/entity/link.entity..ts, backend/src/project/entity/project.entity.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-link.e2e-spec.ts
[(백엔드) 외부 링크 추가 API 구현](https://plastic-toad-cb0.notion.site/API-6375a39cf9794a78a158e5bf922308db?pvs=74)
- 프로젝트 외부 링크 추가 API 구현
- 프로젝트 외부링크 엔티티 추가
- 링크 엔티티를 TypeOrm, NestJS 모듈에 등록
- 프로젝트 링크 추가 레포지토리 메서드 구현
- 프로젝트 링크 추가 서비스 메서드 구현
- 웹소켓 게이트웨이에 프로젝트 링크추가 API 구현
- DTO추가
- 커밋을 다 한 후에 필요없는 import가 들어가 있는것을 확인했습니다. 아직 깃허브에 올리기 전이었기 때문에 이를 수정하는 새로운 커밋을 만들기 보다는 기존의 커밋을 수정하고자 했습니다. 직전의 커밋이 아니었기 때문에 git commit --amend로는 수정이 불가능해 rebase로 해결했는데 이 과정을 [개발일지 - 과거의 특정 커밋에 현재 변경사항을 적용하는 방법](https://plastic-toad-cb0.notion.site/e883c67abd654bca9fc8a68a77f78c92)에 상세히 작성해 놓았습니다~
=> feat: 프로젝트 외부 링크 추가 API 구현

backend/src/project/dto/InitLandingResponse.dto.ts, backend/src/project/dto/LinkCreateRequest.dto.ts, backend/src/project/dto/LinkDeleteRequest.dto.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/test/project/ws-link.e2e-spec.ts, backend/test/project/ws-project-landing-page.e2e-spec.ts
[(백엔드) 외부 링크 추가 API에 대한 유효성 검사](https://plastic-toad-cb0.notion.site/API-7e11d9965c484ea6b7de2d2f9584d71d)
[(백엔드) 랜딩페이지 접속시 외부링크 정보 전송하기](https://plastic-toad-cb0.notion.site/0eb20353097044af9ba123e8302a8dab?pvs=74)
[(백엔드) 외부 링크 삭제 API 구현](https://plastic-toad-cb0.notion.site/API-19e8149a44d3400f8f21be70adb2c173)
- 외부 링크 추가 API에 대한 유효성 검사
- 랜딩페이지 접속시 외부링크 정보 전송하기
- 외부 링크 삭제 API 구현
- 유효하지 않은 URL에 대한 e2e 테스트 추가
- 검증로직 추가
- 랜딩페이지 접속시 프로젝트의 링크 리스트를 반환하는지 확인하는 E2E테스트 추가
- 프로퍼티 이름을 link에서 linkList로 변경
- 프로젝트의 링크를 반환하는 서비스, 레포지토리 구현
- 랜딩페이지 접속시 프로젝트의 링크 리스트를 반환하게 구현
- initLandingDto에서 linkDto클래스 만들어 link의 데이터 형식을 만들도록 구현
- 웹소켓 게이트웨이에서 접속시 link정보 함께 반환하도록 구현
- 링크 삭제 E2E 테스트 추가
- 링크삭제 서비스, 레포지토리 구현
- 링크 삭제 API 구현
- 웹소켓 게이트웨이에서 링크 삭제 요청시 삭제 후 브로드캐스팅하도록 구현
- 링크삭제 요청 DTO 추가
- 유효한 URL임을 판단하는 로직이 컨트롤러에 …
=> feat: 외부링크 유효성검사/랜딩페이지 조회/삭제 API 구현

frontend/src/components/projects/ProjectCard.tsx, frontend/src/components/projects/ProjectCreateInput.tsx, frontend/src/components/projects/ProjectCreateMainSection.tsx, frontend/src/components/projects/ProjectCreateSideBar.tsx, frontend/src/constants/projects.ts, frontend/src/hooks/pages/project/useCreateProjectForm.ts, frontend/src/pages/projects/ProjectCreatePage.tsx
[프로젝트 생성 페이지 애니메이션 수정 및 휠 이벤트 적용](https://plastic-toad-cb0.notion.site/858d54246a684d2eb33290637ce0557c)
- 프로젝트 생성 페이지 애니메이션 수정
- 프로젝트 생성 페이지 휠 이벤트 적용
- 프로젝트 카드 제목에 말줄임 적용
- 회원가입 페이지에 적용한 것처럼 프로젝트 생성 페이지 애니메이션도 css를 통해 실행되도록 수정했습니다.
- ref를 사용할 만큼 무거운 페이지가 아니라 생각했기 때문에 더 확실히 관리하고자 사용자 입력을 ref가 아닌 state로 관리하도록 변경했습니다. 
- 프로젝트 생성 페이지에는 현재 텍스트 입력만 존재하기 때문에 입력하기 편하도록 각 단계가 되었을 때 focus 될 수 있게 했습니다.
=> refactor: 프로젝트 생성 페이지 애니메이션 리팩토링

frontend/src/components/landing/member/LandingMember.tsx, frontend/src/components/landing/member/UserBlock.tsx, frontend/src/constants/storageKey.ts, frontend/src/hooks/common/member/useAwayUser.ts, frontend/src/hooks/common/member/useUpdateUserStatus.ts, frontend/src/hooks/common/socket/useLandingSocket.ts, frontend/src/test/sortMemberByStatus.test.ts, frontend/src/utils/sortMemberByStatus.ts
[상태 변경 피드백 반영](https://plastic-toad-cb0.notion.site/01172628f03e4c2c837f3bffb435f91e)
- 접속 시 서버와 동일한 상태로 적용되도록 수정
- 여러 탭 사용 시 한 탭에서 자리 비움 수동 설정 하더라도 다른 탭에서 마우스를 움직이면 접속 중으로 변경되는 동작 수정
- 상태에 따른 멤버 정렬
- localStorage를 사용해 여러 탭 이용 시 한 탭에서 자리 비움 상태를 설정하면 다른 탭에서도 이벤트 리스너를 제거해 유저 움직임이 감지되지 않도록 수정했습니다. 이를 통해 다른 탭에서 마우스를 움직이거나 해도 자동으로 접속 중으로 바뀌지 않도록 했습니다.
=> fix: 처음 접속 시 서버에서 보내준 상태 반영, 여러 탭 사용 시 수동 자리비움 상태 변경 동작 모두 적용

frontend/src/pages/invite/InvitePage.tsx
[클라이언트에서 참여하기 버튼을 눌렀을 때 10명 프로젝트인 경우 에러 처리](https://plastic-toad-cb0.notion.site/10-4f3d7014866642e3b06d958c885a5793)
- 10명 이상 프로젝트 에러 처리
- 10명 이상인 프로젝트에 참여하려 할 경우 alert를 띄우고 프로젝트 페이지로 이동하도록 했습니다.
=> feat: 10명 이상 프로젝트 에러 처리

backend/src/member/entity/member.entity.ts
[DB 구조 설계](https://plastic-toad-cb0.notion.site/DB-4fb948d693ff4ddcb9d81cec23a790ec)
- unique 조건을 걸면 자동으로 index가 생성되므로 index 데코레이터 삭제
- 기존의 DB를 drop후 create할 때 인덱스 이름의 중복으로 테이블을 구성하는게 불가능한 문제가 발생했습니다. 문제의 원인은 unique 컬럼이며 index 제약조건이 동시에 걸려있는 member테이블의 github_id, username컬럼 각각이 같은 이름의 unique index와 index를 가지고 있어 인덱스 이름이 충돌해 문제가 발생한것으로 파악했습니다.
- 기존의 typeorm 코드입니다.
```
@Index()
@Column({ type: 'int', unique: true, nullable: false })
github_id: number;
```
- 문제가 발생한 쿼리입니다.
```
query failed: CREATE TABLE `member` (
`id` int NOT NULL AUTO_INCREMENT,
`github_id` int NOT NULL,
`github_username` varchar(39) NOT NULL,
`github_image_url` varchar(256) NOT NULL,
`username` varchar(39) NOT NULL,
`position` varchar(20) NOT NULL,
`tech_stack` json NOT NULL,
`created_at` timestamp(6) NOT NULL DEFAULT …
```
=> fix: unique 조건을 걸면 자동으로 index가 생성되므로 index 데코레이터 삭제

frontend/src/components/common/ProfileImage.tsx, frontend/src/components/landing/link/LandingLinkBlock.tsx, frontend/src/hooks/common/landing/useLandingLinkSocket.ts
[링크 추가, 삭제 오류 수정](https://plastic-toad-cb0.notion.site/379011230ff04464a634c1473605c543)
- 외부 링크 오류 수정
- 외부 링크를 추가할 때 이미 추가된 링크가 사라지는 문제, 외부 링크를 삭제할 때 모든 링크가 사라지는 문제를 해결했습니다.
- 외부 링크 이미지가 제대로 보이도록 수정했으며, 미리 정해 놓은 사이트가 아니면 클립 아이콘이 보이도록 수정했습니다.
- 링크 이름이 길어도 링크 크기가 유지되고 대신 말줄임 표시가 되도록 수정했습니다.
=> fix: 외부 링크 추가, 삭제 기능 오류 수정

backend/src/app.module.ts, backend/src/project/dto/epic/EpicDeleteRequest.dto.ts, backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/link/LinkDeleteRequest.dto.ts, backend/src/project/dto/member/MemberUpdateRequest.dto.ts, backend/src/project/dto/memo/MemoColorUpdateRequest.dto.ts, backend/src/project/dto/memo/MemoDeleteRequest.dto.ts, backend/src/project/dto/story/StoryCreateNotify.dto.ts, backend/src/project/dto/story/StoryCreateRequest.dto.ts, backend/src/project/dto/story/StoryDeleteNotify.dto.ts, backend/src/project/dto/story/StoryDeleteRequest.dto.ts, backend/src/project/dto/story/StoryUpdateNotify.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/entity/story.entity.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/src/project/ws-controller/ws-project-story.controller.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts
[스토리 생성, 수정, 삭제 API 구현(백엔드)](https://plastic-toad-cb0.notion.site/API-156056a4f8004585aa40f03a32c17906?pvs=74)
- 스토리 생성, 삭제, 업데이트를 구현하기 위해 스토리 엔티티, 레포지토리, 서비스 작성
- 스토리 생성, 삭제, 업데이트 게이트웨이, 컨트롤러, DTO작성
- 스토리 생성, 삭제, 업데이트 E2E 테스트 작성
- id의 유효성 검사 데코레이터를 IsNumber에서 IsInt로 변경
- 스토리 엔티티 작성
- 스토리을 모듈에 추가
- 스토리 create, delete, update 레포지토리, 서비스 메서드 작성
- 스토리 이벤트를 처리하는 게이트웨이 로직 추가
- 스토리 생성, 삭제, 업데이트를 처리하는 컨트롤러 추가
- 스토리 생성, 삭제, 업데이트에 대해 요청/응답을 확인/생성하는 request, notify DTO 추가
IsNumber 데코레이터는 소수또한 유효하게 처리하기 때문에 Id 프로퍼티의 유효성 검사 데코레이터를 IsInt로 변경
=> feat: 스토리 생성, 수정, 삭제 API 구현

frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/components/backlog/EpicDropdownOption.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryCreateForm.tsx, frontend/src/components/backlog/TaskBlock.tsx, frontend/src/components/backlog/TaskCreateButton.tsx, frontend/src/components/backlog/TaskHeader.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/hooks/pages/backlog/useShowDetail.ts, frontend/src/hooks/pages/backlog/useStoryEmitEvent.ts, frontend/src/pages/backlog/BacklogPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx, frontend/src/types/DTO/backlogDTO.ts, frontend/src/types/common/backlog.ts, frontend/src/utils/changeEpicListToStoryList.ts, frontend/tailwind.config.js
[스토리 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-5b983a7e2ac84de2b4062377717f617c)
- 스토리별 백로그 조회 페이지 컴포넌트 배치
- 스토리 추가 기능 구현
- 반드시 입력되어야 하는 필드가 입력되지 않았을 때 alert를 띄워 입력이 필요함을 알도록 했습니다.
- 프롭스 드릴링을 줄이기 위해 children을 사용해서 TaskList를 StoryList의 children으로 배치했습니다.
- 백로그와 관련된 컴포넌트가 많아졌는데 이를 어떤 폴더 구조를 통해 효율적으로 관리할 수 있을지 고민이 됩니다. Epic, Story, Task, 공용 컴포넌트로 나누는 게 좋을지 잘 모르겠네요. 좀 더 생각해봐야 할 것 같습니다.
- 관심사 및 책임에 따라 컴포넌트를 나누려고 했는데 어느 정도까지 관심사 분리를 해야 할지 나름의 기준이 필요할 것 같습니다. 컴포넌트가 많아지더라도 컴포넌트 내 구조를 더 명확하게 파악할 수 있도록 좀 더 작게 분리하는 것이 좋을지 고민이 필요합니다.
=> feat: 스토리별 백로그 조회, 스토리 추가 기능 구현

frontend/src/components/backlog/EpicDropdownOption.tsx
- 에픽 드롭다운에서 메뉴 클릭 시 드롭다운이 닫히는 문제 해결
- 이벤트 전파를 막는 방식으로 해결했습니다.
=> fix: 에픽 옵션 메뉴를 클릭하면 드롭다운이 닫히는 문제 해결

backend/src/app.module.ts, backend/src/project/dto/task/TaskCreateNotify.dto.ts, backend/src/project/dto/task/TaskCreateRequest.dto.ts, backend/src/project/dto/task/TaskDeleteNotify.dto.ts, backend/src/project/dto/task/TaskDeleteRequest.dto.ts, backend/src/project/dto/task/TaskUpdateNotify.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/entity/project.entity.ts, backend/src/project/entity/task.entity.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/src/project/ws-controller/ws-project-task.controller.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-task.e2e-spec.ts
[태스크 생성/삭제/수정 API 구현](https://plastic-toad-cb0.notion.site/API-6f9a6bd7f19c46ad99a3771e14b3c854?pvs=74)
- 태스크 생성, 삭제, 업데이트 엔티티, 레포지토리, 서비스 작성
- 태스크 생성, 삭제, 업데이트 게이트웨이, 컨트롤러, DTO작성
- 태스크 생성, 삭제, 업데이트 E2E 테스트 작성
- 태스크 엔티티 작성
- 프로젝트 별 고유 태스크 ID를 위한 displayIdCount를 프로젝트 엔티티에 추가
- 태스크를 모듈에 추가
- 태스크 create, delete, update 레포지토리, 서비스 메서드 작성
- 태스크 이벤트를 처리하는 게이트웨이 로직 추가
- 태스크 생성, 삭제, 업데이트를 처리하는 컨트롤러 추가
- 태스크 생성, 삭제, 업데이트에 대해 요청/응답을 확인/생성하는 request, notify DTO 추가
=> feat: 태스크 생성, 수정, 삭제 API 구현

backend/src/project/dto/InitBacklogResponse.dto.ts, backend/src/project/entity/epic.entity.ts, backend/src/project/entity/project.entity.ts, backend/src/project/entity/story.entity.ts, backend/src/project/entity/task.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/ws-controller/ws-project.controller.ts, backend/test/project/ws-backlog-page/ws-init-backlog.e2e-spec.ts
[스토리 조회 API 구현(백엔드)](https://plastic-toad-cb0.notion.site/API-a974a1e261c74ee29705faff8ec339e3?pvs=74)
- 프로젝트, 에픽, 스토리, 태스크 ManyToOne 데코레이터 추가
- 백로그 조회 레포지토리, 서비스 메서드 작성
- initBacklog시 백로그 데이터 응답하도록 컨트롤러 구현, DTO 작성
- 백로그 조회 E2E 테스트 작성
- ManyToOne 관계에서 relation을 걸어 조회가 가능하도록 엔티티에 [epic|story|task]List 프로퍼티추가
- OneToMany, ManyToOne 데코레이터의 인자로 (epic)=>epic.id가 아니라 epic=>epic.storyList 와 같이 서로의 관계를 정확하게 드러내도록 수정
=> feat: backlog 페이지 접속시 백로그 데이터 반환하도록 구현

frontend/src/components/backlog/BacklogStatusDropdown.tsx, frontend/src/components/backlog/CategoryChip.tsx, frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/components/backlog/EpicDropdownOption.tsx, frontend/src/components/backlog/EpicUpdateBox.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryCreateForm.tsx, frontend/src/components/common/ConfirmModal.tsx, frontend/src/constants/event.ts, frontend/src/hooks/pages/backlog/useBacklogInputChange.ts, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/pages/backlog/UnfinishedStoryPage.tsx, frontend/src/types/common/backlog.ts
[에픽 기능 피드백 반영](https://plastic-toad-cb0.notion.site/1b109721e4dd4dd28bdac9b42db4e46c)
[스토리 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-5b983a7e2ac84de2b4062377717f617c?pvs=74)
- 에픽 기능 피드백 반영(에픽 글자 수 제한, 에픽 수정 반영 등)
- 스토리 수정, 삭제 기능 구현
- 노션의 디자인을 차용해 스토리의 에픽, 타이틀, 포인트, 상태를 수정할 수 있도록 했습니다.
- 스토리를 우클릭할 시 삭제 버튼이 나와 삭제할 수 있도록 했습니다. 스토리를 삭제할 때도 해당 스토리에 있는 모든 태스크가 삭제되므로 모달을 통해 한 번 더 삭제 여부를 확인하도록 했습니다.
- 현재 스토리 블록 컴포넌트의 크기가 너무 커서 코드를 이해하기가 쉽지 않고, 버그가 발생할 확률이 높습니다. 컴포넌트 분리가 필요할 것 같은데 컴포넌트를 나누는 기준을 잘 고려해서 나눠야할 것 같습니다.
=> feat: 스토리 수정, 삭제 기능 구현, 에픽 기능 피드백 반영

backend/src/project/dto/epic/EpicCreateRequest.dto.ts, backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/story/StoryCreateRequest.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/dto/task/TaskCreateRequest.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/entity/epic.entity.ts, backend/src/project/entity/story.entity.ts, backend/src/project/entity/task.entity.ts
[스토리 타이틀, 포인트 제약조건 수정하기(백엔드)](https://plastic-toad-cb0.notion.site/e554eeaae433457085b0fa3a23589889?pvs=74)
[에픽 이름 제약조건 수정하기(백엔드)](https://plastic-toad-cb0.notion.site/e3bcc8172e694936b809232e70e64941?pvs=74)
- epic
- name을 1자 이상 10자 이하로 설정
- story
- title을 1자 이상 100자 이하로 설정
- point을 1 포인트 이상 100 포인트 이하로 설정
- task
- title을 1자 이상 100자 이하로 설정
=> feat: epic, story, task 엔티티, DTO에 대해 제약조건 설정

frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryCreateForm.tsx, frontend/src/components/backlog/TaskCreateBlock.tsx, frontend/src/components/backlog/TaskCreateButton.tsx, frontend/src/components/backlog/TaskCreateForm.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/hooks/pages/backlog/useTaskEmitEvent.ts, frontend/src/types/DTO/backlogDTO.ts, frontend/src/types/common/backlog.ts
[태스크 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-9967c3b1ef5d4610bbcbeb4c2b2f887b)
[스토리 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-5b983a7e2ac84de2b4062377717f617c)
- 태스크 생성 API 연동
- 스토리 피드백 반영(스토리 타이틀 글자 수 제한, 스토리 포인트 범위 제한, 스토리 타이틀의 길이가 길 시 말줄임표 표시)
- 태스크를 생성할 때 예상 시간, 실제 시간을 입력하지 않더라도 생성할 수 있도록 했습니다.
- 담당자는 스프린트 중에 분배되도록 하기 위해 미리 입력받지 않도록 했습니다.
=> feat: 태스크 생성 API 연동, 스토리 피드백 반영

backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/member/MemberUpdateRequest.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/util/validation.util.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts
[Patch형태의 업데이트 API에서 변경하는 프로퍼티가 없을경우 업데이트가 실패하도록 변경하기](https://plastic-toad-cb0.notion.site/Patch-API-411a6381874d4ac89b82612b371cfc72?pvs=74)
- Patch형태의 수정 API에서 수정할 프로퍼티가 없으면 유효하지 않은 요청으로 판단하는 유효성검사 추가
- story update API에서 업데이트할 프로퍼티가 존재하지 않을 경우 에러임을 확인하는 테스트 추가
- epic 수정 API에 적용
- story 수정 API에 적용
- task 수정 API에 적용
- member 수정 API에 적용
- 장애가 발생한 케이스에 대한 회귀테스트임
=> feat: Patch형태의 업데이트 API에서 변경하는 프로퍼티가 없을경우 업데이트가 실패하도록 구현

backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/member/MemberUpdateRequest.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/entity/epic.entity.ts, backend/src/project/entity/link.entity..ts, backend/src/project/entity/memo.entity.ts, backend/src/project/entity/story.entity.ts, backend/src/project/entity/task.entity.ts, backend/src/project/util/validation.util.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts
- 상위 테이블 삭제시 유효하지 않은 정보는 함께 삭제되게 구현
- 상위 테이블 삭제에도 유효한 정보(메모-멤버, 태스크-멤버)는 NULL로 설정
=> fix: 계층적 테이블 구조에서 상위 테이블 삭제시 동작 정의

frontend/src/components/backlog/AssignedMemberDropdown.tsx, frontend/src/components/backlog/TaskBlock.tsx, frontend/src/components/backlog/TaskCreateForm.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/hooks/pages/backlog/useTaskEmitEvent.ts
[태스크 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-9967c3b1ef5d4610bbcbeb4c2b2f887b?pvs=74)
- 태스크 수정, 삭제 API 연동
- 스토리 수정, 삭제 API와 동일한 방식으로 태스크 수정, 삭제 API를 연동했습니다. 태스크 또한 태스크 블록 컴포넌트의 크기가 커져 코드 파악이 힘들고, 버그가 발생하기 쉽기 때문에 리팩토링이 필요합니다.
=> feat: 태스크 삭제, 수정 API 연동

backend/src/project/dto/epic/EpicUpdateNotify.dto.ts, backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/member/MemberUpdateRequest.dto.ts, backend/src/project/dto/story/StoryUpdateNotify.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/dto/task/TaskUpdateNotify.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/entity/epic.entity.ts, backend/src/project/entity/link.entity..ts, backend/src/project/entity/memo.entity.ts, backend/src/project/entity/story.entity.ts, backend/src/project/entity/task.entity.ts, backend/src/project/util/validation.util.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-task.e2e-spec.ts
✅ 작업 내용
- update후 notify할 프로퍼티의 여부를 falsy로 체크하는게 아니라 undefined인지 체크하게 변경
- task를 업데이트 할 때 프로퍼티의 값이 falsy값인 경우 테스트 추가
=> fix: patch형태의 update API에서 falsy값인 경우 notify가 되지 않는 버그 수정

frontend/src/components/backlog/AssignedMemberDropdown.tsx, frontend/src/components/backlog/BacklogStatusDropdown.tsx, frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/components/backlog/EpicDropdownOption.tsx, frontend/src/components/backlog/EpicUpdateBox.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/TaskBlock.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/utils/isIntegerOrOneDecimalPlace.ts
[태스크 생성, 수정, 삭제 API 연결](https://plastic-toad-cb0.notion.site/API-9967c3b1ef5d4610bbcbeb4c2b2f887b)
- 태스크 수정 디테일 요구사항 반영
- 타이틀 길이 제한
- 예상 시간, 실제 시간 범위 제한
- 스토리 에픽 수정 문제 해결
- 상태 관리의 오류로 발생하던 에픽 수정 시 한 가지의 에픽만 수정되던 문제를 해결했습니다.
- 스토리의 에픽을 수정해도 반영되지 않던 문제를, 반영 로직을 추가해 해결했습니다.
- 스토리 및 태스크의 상태 드롭다운이 상태 컴포넌트에 가려지는 문제를 해결했습니다.
- 타이틀 길이, 예상 시간, 실제 시간의 범위를 제한해 이를 어길 시 알람을 띄우도록 했습니다.
=> fix: 스토리 에픽 수정 문제 해결, 태스크 수정 시 디테일 요구사항 반영

frontend/src/AppRouter.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/pages/backlog/FinishedStoryPage.tsx, frontend/src/stores/useMemberStore.ts
[완료된 스토리 조회 페이지 구현](https://plastic-toad-cb0.notion.site/f6dcfd3d584a4343b8019b453a1a655c)
- 완료된 스토리 페이지 구현
- 새로고침 시 참가자 모달에 참가자가 없어지는 문제 해결
- 스토리 페이지와 동일한 형식으로 구현했습니다. 다만 완료된 스토리 페이지에서는 스토리를 생성할 수 없고, 이미 완료된 스토리에 태스크를 추가하는 일이 부자연스럽게 느껴지기 때문에 태스크 또한 생성할 수 없도록 했습니다.
=> feat: 완료된 스토리 페이지 구현

backend/package-lock.json, backend/package.json, backend/src/common/decorator/IsLexoRankValue.ts, backend/src/project/dto/InitBacklogResponse.dto.ts, backend/src/project/dto/epic/EpicCreateNotify.dto.ts, backend/src/project/dto/epic/EpicCreateRequest.dto.ts, backend/src/project/dto/epic/EpicUpdateNotify.dto.ts, backend/src/project/dto/epic/EpicUpdateRequest.dto.ts, backend/src/project/dto/story/StoryCreateNotify.dto.ts, backend/src/project/dto/story/StoryCreateRequest.dto.ts, backend/src/project/dto/story/StoryUpdateNotify.dto.ts, backend/src/project/dto/story/StoryUpdateRequest.dto.ts, backend/src/project/dto/task/TaskCreateNotify.dto.ts, backend/src/project/dto/task/TaskCreateRequest.dto.ts, backend/src/project/dto/task/TaskUpdateNotify.dto.ts, backend/src/project/dto/task/TaskUpdateRequest.dto.ts, backend/src/project/entity/epic.entity.ts, backend/src/project/entity/story.entity.ts, backend/src/project/entity/task.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/ws-controller/ws-project-epic.controller.ts, backend/src/project/ws-controller/ws-project-story.controller.ts, backend/src/project/ws-controller/ws-project-task.controller.ts, backend/test/project/ws-backlog-page/ws-epic.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-init-backlog.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-task.e2e-spec.ts
[우선순위 API  구현](https://plastic-toad-cb0.notion.site/API-b243d8a8a8da4287b821fbb199ad995f?pvs=74)
- 에픽 생성, 수정 API에 우선순위 데이터(rankValue)추가
- 스토리 생성, 수정 API에 우선순위 데이터(rankValue)추가
- 태스크 생성, 수정 API에 우선순위 데이터(rankValue)추가
- 백로그 조회 API에 우선순위 데이터(rankValue)추가
-  Epic, Task, Story 생성, 수정시 중복된 rankValue를 서버가 조정해, 조정된 rankValue를 반환하는 로직 구현
- lexorank 패키지 설치
- epic 엔티티
- rankValue 프로퍼티 추가
- 에픽의 rankValue가 project에서 고유하도록 유니크 제약조건 추가
- project 레포지토리, project 서비스, epic컨트롤러에 rankValue 정보 추가
- Epic DTO에 rankValue 정보 추가
- LexoRank형식인지 검증할 수 있는 IsLexoRankValue 데코레이터 추가
- E2E 테스트
- 에픽, 스토리, 태스크, 백로그 테스트에 rankValue정보 추가
- 에픽 테스트에 rankValue update테스트 추가
- story 엔티티
- rankValue 프로퍼티 추가
- 스토리의 rankValue가 project에서 고유하도록 유니크 제약조건 추가
- project 레포지토리, project 서비스의 story 관련 update, create 메서드에 rankValue정보 추가
- …
=> feat: 에픽, 스토리, 태스크 우선순위 API 구현

frontend/package.json, frontend/src/AppRouter.tsx, frontend/src/components/backlog/EpicBlock.tsx, frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryCreateForm.tsx, frontend/src/components/backlog/TaskCreateBlock.tsx, frontend/src/components/backlog/TaskCreateForm.tsx, frontend/src/hooks/pages/backlog/useEpicEmitEvent.ts, frontend/src/hooks/pages/backlog/useStoryEmitEvent.ts, frontend/src/hooks/pages/backlog/useTaskEmitEvent.ts, frontend/src/pages/backlog/EpicPage.tsx, frontend/src/pages/backlog/FinishedStoryPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx, frontend/src/types/DTO/backlogDTO.ts, frontend/src/types/common/backlog.ts, frontend/src/utils/changeEpicListToStoryList.ts, frontend/src/utils/getDragElementIndex.ts, frontend/yarn.lock
[스토리 우선순위 변경 API 연동](https://plastic-toad-cb0.notion.site/API-015c9c6183d84b00997cbc79b4fa1520?pvs=74)
[드래그 앤 드롭 기능 구현](https://plastic-toad-cb0.notion.site/5f1810e74910420cbb7ef52a831711c3)
[에픽 별 스토리 조회 페이지 구현](https://plastic-toad-cb0.notion.site/2d852abad9ac4fc4a77a388392b8ea16)
- 스토리 드래그 앤 드롭 기능 구현(우선순위 변경 기능)
- 에픽별 백로그 페이지 구현
- 이전 버전에서 드래그 앤 드롭 기능을 구현할 때 라이브러리를 사용했지만 이번에는 직접 구현해보고자 라이브러리 사용 없이 구현해봤습니다. UI 상으로는 잘 동작하지만 아직 모듈화를 하지 않아서 태스크, 에픽 드래그 앤 드롭 기능까지 적용하지는 못했습니다. 좀 더 설계하고 모듈화 하는 것이 필요합니다.
=> feat: 스토리 드래그 앤 드롭 기능, 에픽별 백로그 페이지 구현

backend/src/project/entity/story.entity.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts
[우선순위 API  구현](https://plastic-toad-cb0.notion.site/API-b243d8a8a8da4287b821fbb199ad995f?pvs=74)
- 다른 에픽으로의 스토리 rankValue 변경 테스트 삭제
- projectService에서 getAdjustedEpicRankValue함수명을 getAdjustedRankValue으로 변경
- projectService에서 rankValue조정 재시도를 모두 10회로 변경
- 스토리의 rankValue가 프로젝트에서 고유하도록 제약조건 수정
=> fix: 스토리에서 rankValue가 에픽이 아닌 프로젝트내에서 고유하도록 수정

frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx, frontend/src/utils/getDragElementIndex.ts, frontend/src/utils/getNewColor.ts
[프로젝트 회원은 백로그에서 스토리 우선순위를 변경할 수 있다.](https://plastic-toad-cb0.notion.site/43fe3dccfa494dada7fde3588b7389e5)
- 스토리 우선순위 변경 로직 수정
- 스토리별 페이지에서 완료된 스토리 제거
- 에픽 색상 랜덤 지정 로직 수정
- 에픽 드롭다운 길이 설정
- 이전 로직은 index를 기반으로 우선순위를 변경할 스토리를 식별해서 여러 사람이 동시에 다른 스토리의 우선순위를 변경하면 의도하지 않은 스토리가 변경되는 문제가 발생했습니다. 이를 방지하기 위해 스토리의 아이디를 기반으로 식별하는 로직으로 변경했습니다.
- useMemo를 사용해 에픽 색상을 생성하고 있었어서 하나의 에픽을 생성하고 난후 에픽 드롭다운이 닫히지 않으면 계속 똑같은 색상으로 에픽이 생성되었습니다. 이를 상태로 관리하도록 해서 새로운 에픽 생성 시 다시 랜덤한 색상이 배정되도록 했습니다.
=> fix: 스토리 우선순위 변경 로직 수정

backend/package-lock.json, backend/package.json, backend/test/project/join-project.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-epic.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-init-backlog.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-story.e2e-spec.ts, backend/test/project/ws-backlog-page/ws-task.e2e-spec.ts, backend/test/project/ws-landing-page/ws-connection.e2e-spec.ts, backend/test/project/ws-landing-page/ws-join-project.e2e-spec.ts, backend/test/project/ws-landing-page/ws-link.e2e-spec.ts, backend/test/project/ws-landing-page/ws-memo.e2e-spec.ts, backend/test/project/ws-landing-page/ws-project-landing-page.e2e-spec.ts, backend/test/project/ws-landing-page/ws-update-member-status.e2e-spec.ts, backend/test/setup.ts
[백엔드 E2E 테스트 시간 단축하기](https://plastic-toad-cb0.notion.site/E2E-6e0c0a9029d54b9ea2ad36a741be68bf?pvs=74)
- 테스트에서 가용한 포트를 직접 찾도록 구현
- E2E 테스트가 병렬적으로 수행될 수 있도록 구현
- portfinder 라이브러리 추가
- 가용한 포트를 찾아 listen하고, 환경변수로 지정하는 listenAppAndSetPortEnv 메서드 추가
- 테스트에서 사용할 포트를 환경변수로 받도록 변경
- E2E 테스트 속도 54.32% 증가
- 각 테스트가 uuid값으로 임시 테스트 데이터베이스를 생성하고 테스트 완료 후 삭제
- test:e2e명령어 runInBand(순차적 테스트 실행)삭제
- E2E 테스트 시간을 줄이기 위해 테스트케이스마다 서버를 종료했다 다시 실행하는 재실행 로직을 없애는 방법과 병렬적으로 테스트파일을 테스트하는 방법을 고민해 보았습니다.
- 고민의 결론은 아래와 같습니다.
- 테스트케이스 별 서버 재실행 로직은 유지한다.
- 테스트 케이스 마다 서버를 재실행하지 않아도 현재 테스트에서 문재가 발생하지 않으나, 문제가 발생하지 않은 원인이 특정 구현에 의존한다. 따라서 해당 구현이 바뀌거나 메모리의 저장하는 정보가 늘어났을때 테스트가 실패할 수 있고, 실패할 경우 디버깅이 어려울 가능성이 높다고 생각해 테스트케이스별 서버 재실행 로직을 유지하기로 결정함
- 병렬적으로 테스트 파일을 테스트하려면 세가지 조건을 만족해야한다.
- 테스트들이 서버를 공유하면 안된다.
- 기본적인 세팅이 서버를 공유하지 …
=> test: 백엔드 E2E 테스트 시간 단축

frontend/src/components/backlog/DragContainer.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryDragContainer.tsx, frontend/src/components/backlog/TaskDragContainer.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/pages/backlog/EpicPage.tsx, frontend/src/pages/backlog/FinishedStoryPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx
[드래그 앤 드롭 기능 구현](https://plastic-toad-cb0.notion.site/5f1810e74910420cbb7ef52a831711c3)
[태스크 우선순위 변경 API 연동](https://plastic-toad-cb0.notion.site/API-e34b275feccc4e368dd9a63995f43572)
- 태스크 드래그 앤 드롭 로직 작성
- 태스크 우선순위 변경 API 연동
- 태스크의 우선순위를 변경할 수도 있으며, 드래그 앤 드롭으로 해당 태스크의 스토리도 변경되도록 했습니다.
- 현재 한 페이지에 스토리 우선순위 변경, 태스크 우선순위 변경 로직이 모두 들어가 있어서 코드 분리가 필요합니다.
=> feaT: 태스크 드래그 앤 드롭 기능 구현

frontend/src/components/backlog/EpicBlock.tsx, frontend/src/components/backlog/EpicDragContainer.tsx, frontend/src/components/backlog/EpicPageStoryDragContainer.tsx, frontend/src/components/backlog/EpicPageTaskDragContainer.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/hooks/pages/backlog/useBacklogSocket.ts, frontend/src/hooks/pages/backlog/useEpicEmitEvent.ts, frontend/src/pages/backlog/EpicPage.tsx, frontend/src/pages/backlog/FinishedStoryPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx
[에픽 우선순위 변경 로직 작성](https://plastic-toad-cb0.notion.site/73ddbe6ed76740faacea23015ce81745)
[스토리별 페이지, 에픽별 페이지 에러 처리](https://plastic-toad-cb0.notion.site/2bdf163f52534920b62e62e89f7be87b)
- 에픽별 페이지 드래그 앤 드롭 기능 구현
- 에픽이 리스트의 마지막 부분으로 드래그되지 않는 문제 해결
- 스토리, 태스크 토글 기능이 동작하도록 수정
- 에픽 별 페이지에서 스토리 드래그 앤 드롭이 제대로 동작하도록 수정
- 에픽은 에픽별, 스토리는 스토리별, 태스크는 태스크별로 드래그 앤 드롭을 통해 우선순위를 변경하도록 했습니다.
- 서로 연관된 코드가 많아 한 페이지 내에 드래그 앤 드롭 관련 기능이 모두 들어가 있어 복잡성이 높습니다. 리팩토링이 필요합니다.
- 스토리를 드래그할 때 해당 스토리에 속한 태스크도 같이 드래그되지 않기 위해 태스크를 스토리 컴포넌트 외부에 위치하도록 했습니다. 이에 따라 토글된 상태를 리스트로 관리하고 있었는데, 이로 인해 열린 스토리를 드래그하면 원래 열려있던 스토리가 아니라 해당 장소로 드롭된 스토리가 열리는 문제가 발생했습니다. 이를 고치기 위해 리스트를 객체로 변경했고, 겹치지 않기 위해 키를 해당 스토리 또는 태스크를 포함하는 에픽, 스토리의 아이디로 했습니다.
=> feat: 에픽별 페이지 드래그 앤 드롭 기능 구현

frontend/src/AppRouter.tsx, frontend/src/components/account/TechStackInput.tsx, frontend/src/components/projects/ProjectList.tsx
- 루트 페이지 로그인 페이지로 변경
- 플러스 아이콘 표시되도록 수정
- 프로젝트 리스트 페이지에 프로젝트가 없을 경우 프로젝트를 추가해달라는 문구 표시
- 추후 루트 페이지에 다른 요소를 추가할 수도 있을 것이라 생각해 지금은 단순히 TempPage를 로그인 페이지로 변경해놓는 것으로 수정했습니다.
=> fix: 루트 페이지를 로그인 페이지로 변경, 플러스 아이콘 표시, 프로젝트 리스트 페이지 수정

frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/TaskBlock.tsx, frontend/src/components/backlog/common/NumberInputColumn.tsx, frontend/src/components/backlog/common/TextInputColumn.tsx, frontend/src/pages/backlog/EpicPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx
[백로그 컴포넌트 리팩토링](https://plastic-toad-cb0.notion.site/6880c7c2824e43b0aeff40e4db6c1f12)
- 백로그 페이지 컴포넌트 리팩터링
- 드래그 앤 드롭 기능 수정
- 스토리 블록과 태스크 블록에서 중복되는 부분이 있어서 분리했습니다. 분리 후 재사용해 코드 복잡성을 조금이나마 줄이고자 했습니다.
- 에픽별 페이지, 스토리별 페이지에서 각 드래그 항목이 드래그 중 삭제되면 드래그자리에 생기던 줄 표시가 사라지도록 했습니다.
=> refactor: 백로그 페이지 컴포넌트 리팩토링

frontend/src/components/backlog/EpicBlock.tsx, frontend/src/components/backlog/EpicCreateButton.tsx, frontend/src/components/backlog/EpicCreateForm.tsx, frontend/src/components/backlog/EpicDropdown.tsx, frontend/src/components/backlog/StoryBlock.tsx, frontend/src/components/backlog/StoryCreateForm.tsx, frontend/src/components/backlog/TaskBlock.tsx, frontend/src/pages/backlog/EpicPage.tsx, frontend/src/pages/backlog/UnfinishedStoryPage.tsx
[백로그 피드백](https://plastic-toad-cb0.notion.site/29ec6117b508458bb8cc82ddecd43629?pvs=74)
- 백로그 페이지에 있었던 버그 수정
- 아이템 삭제 시 드래그 앤 드롭이 되지 않거나 삭제 버튼이 아래에 있어 클릭되지 않는 등의 버그를 수정했습니다.
=> fix: 백로그 페이지 기능 수정

backend/src/member/entity/member.entity.ts, backend/src/project/dto/InitLandingResponse.dto.ts, backend/src/project/entity/project-member.entity.ts, backend/src/project/enum/MemberRole.enum.ts, backend/src/project/enum/MemberStatus.enum.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.spec.ts, backend/src/project/service/project.service.ts, backend/test/project/ws-landing-page/ws-role.e2e-spec.ts
[팀장 추가하기](https://plastic-toad-cb0.notion.site/7fd2641c9efb4e1e8a45abf984fd1e66?pvs=74)
- feat: 프로젝트의 회원 엔티티에 Role추가
- style: 들여쓰기 수정
- test: 프로젝트의 회원 role 추가로 인한 테스트 변경
- 프로젝트 생성 시 해당 회원의 role이 LEADER가 되도록 구현
- 프로젝트 생성 시 해당 회원의 role이 MEMBER가 되도록 구현
- MemberRole Enum 추가
- project-member Entity에 role 추가
- 서비스, 레포지토리에 role추가
- InitLandingResponse DTO에서 role 정보를 함께 반환하도록 구현
- role관련 E2E 테스트 추가
- 개발서버에서 기존의 데이터에도 일관된 role 규칙을 부여하기 위해 개발서버에 접속해 아래의 쿼리를 실행시켰습니다.
- 테이블에 role 컬럼 추가
```jsx
ALTER TABLE project_to_member
ADD COLUMN role ENUM('LEADER', 'MEMBER') NOT NULL;
```
- 첫 번째로 참여한 회원은 `LEADER`, 나머지는 `MEMBER`로 설정하는 쿼리 작성
- 모든 회원의 role을 MEMBER로 설정한다.
```jsx
UPDATE project_to_member SET role = 'MEMBER';
```
- 프로젝트에 가장 먼저 가입한 회원을 LEADER로 만든다.
- 서브쿼리는 project별 가장 먼저 가입한 시간을 찾는 쿼리임
```jsx
UPDATE …
```
=> feat: 프로젝트에 팀장 추가

backend/src/project/dto/project-info/ProjectInfoUpdateNotify.dto.ts, backend/src/project/dto/project-info/ProjectInfoUpdateRequest.dto.ts, backend/src/project/dto/setting-page/InitSettingResponse.dto.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/src/project/ws-controller/ws-project-info.controller.ts, backend/src/project/ws-controller/ws-project.controller.ts, backend/test/project/ws-setting-page/ws-project-landing-page.e2e-spec.ts, backend/test/project/ws-setting-page/ws-update-project-info.e2e-spec.ts
[세팅페이지 접속, 프로젝트 정보 수정 API 구현](https://plastic-toad-cb0.notion.site/API-82679bea56dd4eb9914edeb40ce5aabd?pvs=4)
ex)
- 설정 페이지 입장 API 구현
- 프로젝트 리더가 아닌 회원이 설정페이지를 접속시 웹소켓 연결을 끊도록 구현
- 프로젝트 이름, 주제 수정 API 구현
- joinSetting 이벤트 추가
- 설정 페이지 입장시 프로젝트의 이름, 주제, 회원 데이터 응답 구현
- 설정페이지 응답 DTO 추가
- E2E테스트 추가
- 프로젝트 리더인지 확인하는 서비스 구현
- 프로젝트 리더가 아닌 회원이 설정 페이지 접속시 웹소켓 연결 끊도록 구현
- 리더가 아닌 회원이 설정페이지 입장 하는 E2E 테스트 추가
- 프로젝트 이름, 주제 수정 레포지토리, 서비스 구현
- 리더가 아닌 인원이 수정시 웹소켓 연결을 끊도록 구현
- 프로젝트 이름, 주제 수정 시 랜딩, 설정 페이지에 있는 회원들에게 알림을 주도록 구현
- 프로젝트 이름, 주제 수정 DTO 추가
- 프로젝트 이름, 주제 수정 E2E테스트 추가
=> feat: 세팅페이지 접속 API, 프로젝트 이름,주제 수정 API 구현

frontend/src/AppRouter.tsx, frontend/src/components/backlog/BacklogHeader.tsx, frontend/src/components/landing/member/LandingMember.tsx, frontend/src/components/setting/InformationInput.tsx, frontend/src/components/setting/InformationSettingSection.tsx, frontend/src/components/setting/MemberBlock.tsx, frontend/src/components/setting/MemberSettingSection.tsx, frontend/src/components/setting/ProjectDeleteModal.tsx, frontend/src/components/setting/ProjectDeleteSection.tsx, frontend/src/hooks/common/landing/useLandingProjectSocket.ts, frontend/src/hooks/common/socket/useSocket.ts, frontend/src/hooks/pages/setting/useSettingProjectInfoSocket.ts, frontend/src/hooks/pages/setting/useSettingProjectSocket.ts, frontend/src/hooks/pages/setting/useSettingSocket.ts, frontend/src/pages/setting/SettingPage.tsx, frontend/src/stores/useMemberStore.ts, frontend/src/test/sortMemberByStatus.test.ts, frontend/src/types/DTO/landingDTO.ts, frontend/src/types/DTO/settingDTO.ts, frontend/src/types/common/setting.ts
[주제 수정 API 연결](https://plastic-toad-cb0.notion.site/API-b891274ee2a04397a0ca093fa906932a)
[이름 수정 API 연결](https://plastic-toad-cb0.notion.site/API-488a58416e054f79be74d8ddd1e7f79b)
- 세팅 페이지 구현
- 주제 수정, 이름 수정 API 연결
- 피그마 디자인대로 세팅 페이지를 퍼블리싱 했습니다.
- API 명세에 맞게 프로젝트 주제와 이름을 수정할 수 있도록 연결했습니다.
- 세팅 페이지에서 이름 및 주제를 변경하면 랜딩 페이지에도 반영되도록 했습니다.
=> feat: 세팅 페이지, 프로젝트 제목, 주제 수정 기능 구현

backend/src/project/dto/invite-link/InviteLinkUpdateRequest.dto.ts, backend/src/project/dto/invite-link/InviteLinkUpdateResponse.dto.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/src/project/ws-controller/ws-project-invite-link.controller.ts, backend/test/project/ws-landing-page/ws-invite-link.e2e-spec.ts
[초대링크 변경 API 구현](https://plastic-toad-cb0.notion.site/API-f9e96ad74ebc41ffb4ac8502cdd810fd?pvs=4)
- 컨트롤러, 서비스, 레포지토리에서 초대링크 업데이트 메서드 구현
- 리더인 경우, 리더가 아닌경우 각각에 대한 초대링크 업데이트 E2E 테스트 추가
=> feat: 초대링크 변경 API 구현

backend/src/project/dto/project-info/ProjectDeleteNotify.dto.ts, backend/src/project/dto/project-info/ProjectDeleteRequest.dto.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/src/project/websocket.gateway.ts, backend/src/project/ws-controller/ws-project-info.controller.ts, backend/src/project/ws-controller/ws-project.controller.ts, backend/test/project/ws-setting-page/ws-delete-project.e2e-spec.ts
[프로젝트 삭제 API 구현](https://plastic-toad-cb0.notion.site/API-833fb4515de040b7bd9b568b51c04614?pvs=74)
- feat: 프로젝트 삭제 API 구현
- fix: 'joinLanding' 이벤트 처리 로직 중 잘못된 방을 나가는 로직 수정
- 게이트웨이
- 프로젝트 삭제관련 라우팅 로직 추가
- 프로젝트 삭제시 해당 프로젝트의 네임스페이스 Map 삭제하도록 구현
- 컨트롤러
- 프로젝트 삭제 메서드 추가
- 삭제 알림 보내고 1초 후 프로젝트 삭제하는 로직 구현
- 서비스
- 프로젝트 삭제 메서드 추가
- 레포지토리
- 프로젝트 삭제 메서드 추가
- 프로젝트 삭제 E2E 테스트 추가
=> feat: 프로젝트 삭제 API 구현

backend/src/project/dto/ProjectInvitePreviewResponse.dto.ts, backend/src/project/dto/service/ProjectBriefInfo.dto.ts, backend/src/project/project.controller.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/test/project/get-project-preview.e2e-spec.ts
[프로젝트 정보 반환 API 개발(UUID로 조회)](https://plastic-toad-cb0.notion.site/API-UUID-106f5552133380a783d5e33531eeb6f0)
- 컨트롤러
- 프로젝트 초대 브리뷰 반환하는 메서드 구현
- 서비스
- 초대링크로 프로젝트의 일부 정보를 반환하는 메서드 구현
- 레포지토리
- 프로젝트, 프로젝트 회원을 조인해서 반환하는 메서드 구현
- 프로젝트 프리뷰 조회 E2E 테스트 추가
- 서비스에서 프로젝트의 전체 정보를 조회해 컨트롤러에서 필요한 정보를 선별해서 반환하는게 아니라 서비스에서 일부분의 정보만을 반환하는 서비스 메서드를 만들었습니다.
- 왜냐하면 프로젝트의 멤버가 아닌 일반 회원이 컨트롤러에서 서비스의 전체정보 메서드를 사용했을때 추후 컨트롤러의 구현이 바뀌는 이유로 프로젝트의 원치않은 정보가 노출되는것이 우려되었기 때문입니다.
- 따라서 서비스는 Project 엔티티 전체를 반환하지 않고, DTO 클래스로 `ProjectBriefInfoDto`를 정의해 초대를 요청하는 회원이 볼수있는 수준의 정보만을 제공하게 구현했습니다.
=> feat: 초대링크로 프로젝트의 프리뷰 조회하는 API 구현

backend/src/app.module.ts, backend/src/project/dto/ProjectJoinRequest-Request.dto.ts, backend/src/project/entity/project-join-request.entity.ts, backend/src/project/entity/project.entity.ts, backend/src/project/project.controller.ts, backend/src/project/project.module.ts, backend/src/project/project.repository.ts, backend/src/project/service/project.service.ts, backend/test/project/post-join-request.e2e-spec.ts
[프로젝트 참여 요청 API 구현](https://plastic-toad-cb0.notion.site/API-106f5552133380b79c8de9737aa49c8a?pvs=74)
- 엔티티
- 프로젝트 참여요청 엔티티 추가
- 프로젝트 엔티티에 프로젝트 참여요청 프로퍼티 추가
- 레포지토리에서 DB에 프로젝트 참여요청 생성 메서드 추가
- 서비스에서 프로젝트 참여요청 생성 메서드 추가
- 컨트롤러에서 프로젝트 참여요청 제출 메서드 추가
- 프로젝트 참여요청 E2E 테스트 추가
- 성공 상황
- 인증실패 상황
- 유효하지 않은 프로젝트 링크 상황
- 이미 회원인 유저가 요청한 상황
- 이미 참여요청한 유저가 다시 참여요청한 상황
- E2E 테스트를 보다 잘 읽히도록 함수내의 추상화 수준을 동일하게 작성하려고 시도해보았습니다. 확실히 소설처럼 쭉 읽으면 어떤 로직인지 파악할 수 있어 괜찮은것같습니당. 앞으로 테스트 뿐만 아니라 모든 코드를 추상화 수준을 신경써서 작성하면 가독성 측면에서 많은 향상이 있을것같아요. 감사합니다~
=> feat: 프로젝트 참여요청 API 구현
