boostcampwm2023/web10-Lesser

- FE/src/components/common/ProgressBar/ProgressBar.tsx
- FE/src/components/sprint/ColumnBoard.tsx
- FE/src/components/sprint/KanbanBoard.tsx
- FE/src/components/sprint/TaskCard.tsx
- FE/src/pages/sprint/SprintPage.tsx
- LES-112 [FE] 칸반보드를 렌더링하는 코드를 작성한다.
칸반보드를 볼 수 있는 페이지를 생성했습니다.
그 과정에서 생성된 컴포넌트
- ProgressBar
- KanbanBoard
- ColumnBoard
- TaskCard
- SprintPage
- 화면에서 확인할 수 있도록 하는 데이터를 태그 내에 바로 적어야 할지, 임시 데이터를 만들어서 이를 이용해야 할지 고민이 되었습니다. api가 없는 상태에서 어떻게 하는 게 효율적일까요? 코드가 더 깔끔한 것은 어느 방법일까요?
- 현재는 많은 타입이 없어서 컴포넌트 내에 타입을(인터페이스) 바로 정의했는데, 이를 type 폴더 안에 정의해야 할지 고민이 됩니다. props같은 것은 컴포넌트에 정하는 게 좋을 것 같은데 어느 정도까지 다른 폴더로 이동할지 정해야 할 것 같습니다.
> 칸반보드를 확인하는 스프린트 페이지 코드 작성

- BE/src/backlogs/backlogs.controller.ts
- BE/src/backlogs/backlogs.service.ts
- BE/src/dto/create-backlogs-epic.dto.ts
- BE/src/dto/create-backlogs-story.dto.ts
- BE/src/dto/create-backlogs-task.dto.ts
- BE/src/dto/delete-backlogs-epic.dto.ts
- BE/src/dto/delete-backlogs-story.dto.ts
- BE/src/dto/delete-backlogs-task.dto.ts
- BE/src/dto/update-backlogs-epic.dto.ts
- BE/src/dto/update-backlogs-story.dto.ts
- BE/src/dto/update-backlogs-task.dto.ts
- BE/src/entities/story.entity.ts
- BE/src/entities/task.entity.ts
LES-77 에픽을 삭제시 하위 스토리와 태스크가 모두 삭제된다.
LES-87 에픽의 제목을 수정할 수 있다.
LES-78 스토리을 삭제할 수 있고, 스토리를 삭제하면 하위의 태스크가 모두 삭제된다.
LES-79 스토리의 제목을 수정할 수 있다
LES-81 태스크를 삭제 할 수 있다.
LES-86 태스크의 제목, 상태, 담당자, 인수조건, 태스크포인트를 수정할 수 있다.
* epic, story, task 수정, 삭제 구현
* 클래스명을 파스칼케이스로 통일하였습니다.
* 상위개념(story의 상위개념은 Epic)이 삭제되었을때 연쇄적으로 삭제되는게 맞다고 생각해 onDelete Cascade를 걸어놓았습니다.
* 추후 soft delete로 변경할 예정입니다.
항상 감사합니다 ~
> 백로그 수정, 삭제

- BE/src/backlogs/backlogs.controller.ts
- BE/src/backlogs/backlogs.service.ts
- BE/src/dto/create-backlogs-epic.dto.ts
- BE/src/dto/create-backlogs-story.dto.ts
- BE/src/dto/create-backlogs-task.dto.ts
- BE/src/dto/delete-backlogs-epic.dto.ts
- BE/src/dto/delete-backlogs-story.dto.ts
- BE/src/dto/delete-backlogs-task.dto.ts
- BE/src/dto/update-backlogs-epic.dto.ts
- BE/src/dto/update-backlogs-story.dto.ts
- BE/src/dto/update-backlogs-task.dto.ts
- BE/src/entities/story.entity.ts
- BE/src/entities/task.entity.ts
- BE/src/main.ts
태스크없음
* epic 생성버그픽스
* 백엔드 요청 경로에 API 접두사 추가
> 백엔드 요청 경로에 API추가, epic 생성 버그픽스

- FE/Dockerfile
- FE/conf/conf.d/default.conf
LES-134 Jenkins 및 Docker를 이용한 CI/CD 자동배포
- 원격 서버에서 프론트엔드 코드 자동 배포를 위해 FE 디렉토리에 Dockerfile, nginx conf 파일을 추가하였습니다.
- develop/FE 브랜치에 변경사항이 생기면 원격 서버의 젠킨스가 이를 Github Webhook으로 감지하여 프론트엔드 컨테이너를 다시 빌드, 실행시킵니다. 상세 내용은 아래와 같습니다.
- 웹훅으로 연결된 깃허브 레포의 브랜치에서 변경이 감지되면 젠킨스는 설정된 shell script를 실행시킨다.
- 위에서 설정한 shell script에 의해 기존 컨테이너를 stop하고, Dockerfile을 찾아서 다시 컨테이너를 실행한다.
- 위에서 설정한 Dockerfile에서 소스코드를 복사해오므로 변경된 소스코드를 사용하여 빌드를 진행하게 된다.
- node v20.9.0을 빌더로 사용, FE 디렉토리의 소스코드를 번들링
- dist 디렉토리에 번들링된 FE 코드를 nginx에서 서빙할 수 있도록 /usr/share/nginx/html 디렉토리로 복사
- 컨테이너에서 기본으로 설정된 nginx conf 파일을 삭제하고 직접 설정한 nginx conf 파일로 교체하기 위해, 교체될 conf 파일을 작성한다.
- 최상위 디렉토리 안에 `conf/conf.d/default.conf` 파일 생성
> 프론트엔드 CI/CD 자동배포 설정

- BE/Dockerfile
LES-136 NestJS 서버를 테스트 DB에 연결
LES-138 NestJS 서버를 Jenkins로 자동 빌드, 도커 컨테이너로 올리기
원격 서버에서 백엔드 코드 자동 배포를 위해 BE 디렉토리에 Dockerfile을 추가하였습니다.
develop/BE 브랜치에 변경사항이 생기면 원격 서버의 젠킨스가 이를 Github Webhook으로 감지하여 백엔드 컨테이너를 다시 빌드, 실행시킵니다.
- 웹훅으로 연결된 develop/BE 브랜치에서 변경이 감지되면 젠킨스는 설정된 shell script를 실행시킨다.
- 위에서 설정한 shell script에 의해 기존 컨테이너를 stop하고, Dockerfile을 찾아서 다시 컨테이너를 실행한다.
- 위에서 설정한 Dockerfile에서 소스코드를 복사해오므로 변경된 소스코드를 사용하여 빌드를 진행하게 된다.
- 젠킨스에서 도커 컨테이너를 실행시키는 script에서 환경변수를 넣어준다.
> 백엔드 CI/CD 자동배포 설정

- BE/Dockerfile
LES-136 NestJS 서버를 테스트 DB에 연결
LES-138 NestJS 서버를 Jenkins로 자동 빌드, 도커 컨테이너로 올리기
백엔드 Dockerfile에서 복사되는 파일의 경로를 수정하였습니다.
> 백엔드 Dockerfile 수정

- BE/src/main.ts
fix: [swagger] 스웨거 API 긴급수정
/swagger -> /api/swagger로 수정함
> 스웨거 API 수정

- FE/src/assets/icons/CheckIcon.tsx
- FE/src/assets/icons/ChevronDownIcon.tsx
- FE/src/assets/icons/ChevronRightIcon.tsx
- FE/src/assets/icons/ClosedIcon.tsx
- FE/src/assets/icons/EditIcon.tsx
- FE/src/assets/icons/PlusIcon.tsx
- FE/src/components/backlog/BlockFrom.tsx
- FE/src/components/backlog/EpicBlock.tsx
- FE/src/components/backlog/StoryBlock.tsx
- FE/src/components/backlog/TaskBlock.tsx
- FE/src/components/backlog/TaskModal.tsx
- FE/src/hooks/useBlock.tsx
- FE/src/pages/backlog/BacklogPage.tsx
- FE/src/types/backlog.ts
- FE/src/types/icon.ts
- FE/tailwind.config.js
LES-85 [FE] 태스크 생성/수정 모달을 띄우는 코드를 작성한다.
LES-88 [FE] 에픽의 제목을 편집하는 버튼을 만든다.
LES-90 [FE] 스토리의 제목을 편집하는 버튼을 만든다.
- Task 생성하기 버튼 클릭 시 나오는 모달 창 구현
- 에픽과 스토리의 제목 편집 기능 구현
- 백로그 페이지 전체적인 디자인 적용
> Task Modal 구현

- FE/package.json
- FE/src/App.tsx
- FE/src/main.tsx
- FE/src/pages/BacklogPage.tsx
- FE/src/pages/LoginPage.tsx
- FE/src/pages/MainPage.tsx
- FE/src/pages/ProjectPage.tsx
- FE/src/pages/ReviewPage.tsx
- FE/src/pages/SprintPage.tsx
- FE/yarn.lock
[LES-160](https://boostcamp-lesser.atlassian.net/browse/LES-160) [FE] react 개발에 필요한 모듈을 설치한다.
[LES-161](https://boostcamp-lesser.atlassian.net/browse/LES-161) [FE] react-router를 React에 적용한다.
react-router를 설치하여, 실제 클라이언트의 url에 따라 화면을 분기처리 진행
- `/login`, `/project` : 자체적인 페이지 컴포넌트를 렌더링
- `/backlog`, `/sprint`, `/review` : sidebar 컴포넌트를 포함(현재는 "main page" 텍스트로 대체)하는 MainPage 내에서 중첩 라우팅
예시 화면)
/login
/review
> React 환경 설정

- FE/src/apis/api.ts
- [LES-139] customAxios 함수 작성
- axios 요청을 보낼 수 있는 인스턴스를 만들었습니다. apis/api.ts에 있습니다.
- 받고 나서 환경변수 설정을 해주셔야 합니다.
- vite-env.d.ts 폴더에 추가
``` typescript
/// <reference types="vite/client" />
interface ImportMetaEnv {
readonly VITE_BASE_URL: string;
}
interface ImportMeta {
readonly env: ImportMetaEnv;
}
```
- .env 또는 .env.local 파일을 root 폴더에 생성 후 아래 추가
```
VITE_BASE_URL=https://lesser-project.site/api/
```
> 기본 axios 요청 인스턴스 생성

- FE/src/components/project/ProjectCard.tsx
- FE/src/pages/ProjectCreatePage.tsx
- FE/src/pages/ProjectPage.tsx
1. 문자열이 들어간 div tag를 p tag로 변경
- ProjectCard 컴포넌트
- ProjectPage 컴포넌트
> ProjectPage 리팩토링 : tag 종류 변경

- BE/package-lock.json
- BE/package.json
- BE/src/app.module.ts
- BE/src/common/lesser-jwt/constants.ts
- BE/src/common/lesser-jwt/lesser-jwt.module.ts
- BE/src/common/lesser-jwt/lesser-jwt.service.spec.ts
- BE/src/common/lesser-jwt/lesser-jwt.service.ts
- BE/src/main.ts
LES-171 [BE] 로그인 성공시 JWT 토큰(Access, Refresh) 발급하여 클라이언트에게 반환
1. CORS정책을 전체허용으로 임시설정함
1. 유저 로그인유지를 위한 JWT모듈 개발
2. Access Token, Refresh Token을 발급받을 수 있음
3. Access Token을 고려한 토큰에서 아이디 추출하는 로직
4. Refresh TOken을 고려한 토큰 유효성검사로직
* 데모를 위해 일단 CORS를 모두 허용하게 설정했습니다. 추후에 변경하겠습니다.
* JWT모듈을 추가했습니다. 확장성보다는 현재프로젝트에 알맞게 제작했습니다.
* 항상 감사합니다 ~
> CORS설정과 JWT 모듈 개발

- FE/src/apis/api.ts
- FE/src/components/project/ProjectCreateForm.tsx
- FE/src/components/project/ProjectProcessText.tsx
- FE/src/hooks/useProjectForm.tsx
- FE/src/pages/ProjectCreatePage.tsx
- FE/tailwind.config.js
[LES-153] [FE] 유저가 프로젝트 이름을 작성하는 input을 생성한다
[LES-155] [FE] 프로젝트 생성을 위한 POST request를 생성하는 비즈니스 로직을 생성한다.
[LES-152] [FE] 유저가 작성한 데이터를 추출 혹은 저장하는 비즈니스 로직을 작성
[LES-157] [FE] 프로젝트를 생성 페이지를 렌더링 하는 코드를 작성한다.
1. 프로젝트를 생성하는 페이지 작성
- 프로젝트 제목 입력 화면
- 만일 사용자가 빈 값을 입력한 경우, 값을 입력해달라는 alert를 화면에 띄운다.
- 프로젝트 주제 입력 화면
- 만일 사용자가 빈 값을 입력한 경우, 값을 입력해달라는 alert를 화면에 띄운다.
- 프로젝트 멤버 입력의 경우, 이번 데모 포함 내용이 아니기에 다음 데모에 작성 예정
2. 프로젝트 생성 데이터(제목, 주제)를 서버에 전달 후 백로그 페이지로 이동(임시)하는 코드 작성
> 프로젝트 생성 코드 작성

- BE/src/projects/dto/Project.dto.ts
- BE/src/projects/projects.module.ts
- BE/src/projects/projects.service.ts
1. 기존프로젝트 조회의 응답에  프로젝트 태스크개수 추가
2. 빠른구현을 위한 비효율적인 로직을 작성함. 추후 수정예정
> 프로젝트 태스크개수 추가구현

- BE/src/members/members.module.ts
- BE/src/members/members.service.ts
LES-168 [BE] 깃허브 OAuth 회원가입
LES-169 [BE] 깃허브 OAuth 로그인
환경변수를 불러오는 모듈을 ConfigModule로 수정하였습니다.
> 환경변수 불러오는 모듈을 ConfigModule로 수정

- FE/.eslintrc
- FE/src/components/backlog/EpicBlock.tsx
- FE/src/components/backlog/StoryBlock.tsx
- FE/src/components/backlog/TaskBlock.tsx
- FE/src/components/backlog/TaskModal.tsx
- FE/src/hooks/useBlock.tsx
- FE/src/pages/BacklogPage.tsx
- FE/src/types/backlog.ts
- [LES-131] [FE] 백로그 데이터를 가져오는 API를 연동한다.
- [LES-65] [FE] 에픽을 추가하는 버튼과 API를 연결하여 기능을 완성한다.
- [LES-80] [FE] 스토리를 추가하는 버튼과 API를 연결하여 기능을 완성한다.
- [LES-82] [FE] 태스크 모달 내 생성 버튼과 API를 연결하여 기능을 완성한다.
- [LES-89] [FE] 에픽의 제목을 편집하는 버튼과 API를 연결한다.
- [LES-91] [FE] 스토리의 제목을 편집하는 버튼과 API를 연결한다.
- [LES-94] [FE] 태스크의 제목을 편집하는 버튼과 API를 연결한다.
API 연동을 통해 백로그 데이터를 가져오고, 에픽, 스토리, 태스크에 대한 추가, 편집 기능을 구현
> 백로그 API 연동

- BE/src/backlogs/backlogs.controller.ts
- BE/src/backlogs/backlogs.service.ts
> feat: [backlog-read] 백로그 중복권한체크 제거

- FE/src/components/review/DonutChart.tsx
- FE/src/components/review/ReviewChart.tsx
- FE/src/components/review/ReviewHeader.tsx
- FE/src/components/review/ReviewReminiscing.tsx
- FE/src/components/review/ReviewSprint.tsx
- FE/src/index.css
- FE/src/pages/ReviewPage.tsx
[LES-221] 유저는 "스프린트 정보" 탭을 클릭하면 스프린트 정보를 확인할 수 있다.
[LES-222] 유저는 "차트" 탭을 클릭하면 번다운 차트를 확인할 수 있다.
[LES-222] 유저는 "회고란" 탭을 클릭하면 작성된 회고를 확인할 수 있다.
회고 페이지에서 스프린트 정보, 차트, 회고란을 확인할 수 있는 코드를 작성하였습니다.
> 회고 페이지 레이아웃 작성

- FE/package.json
- FE/src/assets/icons/ChevronDownIcon.tsx
- FE/src/components/review/ReviewChart.tsx
- FE/src/components/review/ReviewHeader.tsx
- FE/src/components/review/ReviewSprint.tsx
- FE/src/components/review/ReviewSprintInfo.tsx
- FE/yarn.lock
[LES-221] 유저는 "스프린트 정보" 탭을 클릭하면 스프린트 정보를 확인할 수 있다.
[LES-222] 유저는 "차트" 탭을 클릭하면 번다운 차트를 확인할 수 있다.
recharts 라이브러리를 사용해서 번다운 차트를 구현하였습니다.
react 컴포넌트를 기반으로 하고 사용자 정의 차트를 쉽게 만들 수 있어서 recharts 라이브러리를 사용했습니다.
> 회고 페이지 번다운 차트 구현

- FE/src/App.tsx
- FE/src/components/common/SideNavigationBar.tsx
- FE/src/components/review/DonutChart.tsx
- FE/src/components/review/ReviewChart.tsx
- FE/src/components/review/ReviewHeader.tsx
- FE/src/components/review/ReviewSprint.tsx
- FE/src/data/review.json
- FE/src/main.tsx
- FE/src/pages/ReviewPage.tsx
- FE/src/types/review.ts
- [LES-214] 프로젝트 id를 요청에 담아 보내고, 종료된 스프린트 목록, 각 스프린트의 정보를 받아온다.
- [LES-216] /review 페이지 접근시 최초 화면은 종료된 스프린트 목록 중 최신 스프린트 정보를 노출한다.
- [LES-217] 선택된 1개의 스프린트에 대한 완료 태스크 목록, 미완료 태스크 목록을 보여준다.
- [LES-219] 드롭다운에서는 종료된 스프린트의 실제 종료일 기준으로 내림차순 정렬해서 보여준다.
스프린트 정보와 차트 탭의 API를 연동했습니다.
> 스프린트 정보와 차트 API 연동

- FE/src/pages/LoginPage.tsx
> style: 로그인 페이지 세로 길이 수정

- FE/src/components/sprint/SprintBacklogSetting.tsx
- FE/src/constants/constants.tsx
- FE/src/pages/sprint/SprintCreatePage.tsx
- 스프린트 시작 페이지 뼈대만 생성했습니다. 여기에 스프린트 제목 및 기간 입력 컴포넌트와 스프린트 백로그 설정 컴포넌트를 생성해서 연결하면 됩니다.
- 라우터 연결은 하지 않았습니다.
> 스프린트 시작 페이지 레이아웃 생성

- BE/src/reviews/dto/Review.dto.ts
회고글 작성시 srintId, content 값을 받도록 CreateReviewRequestDto 수정
> 회고글 작성시 srintId, content 값을 받도록 수정

- BE/src/reviews/dto/SprintReviewResponse.dto.ts
- BE/src/reviews/reviews.service.ts
- 컴포넌트 재사용을 위해 회고 페이지 조회 API 스펙 변경
> 회고 페이지 조회 API 스펙 변경

- BE/src/members/dto/login-request.dto.ts
- BE/src/members/dto/login.dto.ts
- BE/src/members/members.controller.ts
- BE/src/members/members.service.ts
로그인 성공시 회원 id, username, imageUrl 추가적으로 반환
> 로그인 성공시 회원정보 반환

- FE/src/apis/Project/index.ts
- FE/src/hooks/pages/project/useSearchUsername.ts
- FE/src/hooks/queries/project/useGetMyProjects.ts
- FE/src/hooks/queries/project/usePostNewProject.ts
- Jenkins 빌드 중 project api를 호출하지 못하는 문제가 발생하여, index 호출과 관련되 에러 여부를 확인하기 위해 index 파일을 삭제하고 직접 각 api 함수를 호출 하도록 코드를 작성
> fix: api 호출 에러 수정

- FE/src/apis/sprint/fetchPostSprint.ts
- FE/src/components/sprint/TaskCard.tsx
- FE/src/components/sprint/sprintCreate/SprintBacklogComponent.tsx
- FE/src/components/sprint/sprintCreate/SprintBacklogSetting.tsx
- FE/src/components/sprint/sprintCreate/SprintGoalSetting.tsx
- FE/src/hooks/queries/sprint/usePostNewSprint.ts
- FE/src/pages/sprint/SprintCreatePage.tsx
- FE/src/types/sprint.ts
- [LES-243] 스프린트 생성 API 연결
- 스프린트 생성 API 연동했습니다. 생성하면 sprint페이지로 이동하도록 했습니다.
> 스프린트 생성 API 연결

- FE/src/App.tsx
- FE/src/pages/ReviewPage.tsx
1. 내 프로젝트 내 프로젝트 목록 보기: /projects
내 프로젝트 생성: /projects/create
2. 백로그 백로그 페이지: /projects/:id/backlog
3. 스프린트 스프린트 칸반 보드 페이지 : /projects/:id/sprint
스프린트 생성 페이지 : /projects/:id/sprint/create
4. 리뷰 스프린트 결과 페이지 : /projects/:id/review/sprint
차트 페이지 : /projects/:id/review/chart
기록 페이지 : /projects/:id/review/write
> fix: 클라이언트 url 수정

- FE/src/components/sprint/sprintCreate/SprintGoalSetting.tsx
오늘 날짜 포함한 이전 날짜를 선택하면 자동으로 다음 날로 설정
> feat: [sprint-create] 스프린트 종료일 설정 기능 구현

- FE/src/components/common/NavigationButton.tsx
- 모든 리뷰 페이지에서 네비게이션이 제대로 포커싱되도록 수정했습니다.
- 그런데 직므은 굉장히 확장성이 좋지 않게 로직이 짜여져 있어서 수정이 필요합니다.
```typescript
const isSameURL = () => {
const currentUriList = currentURI.split('/');
const pageUriList = pageURI(id).split('/');
const currentUriLength = currentUriList.length;
const pageUriLength = pageUriList.length;
if (currentUriLength === pageUriLength && currentUriList[currentUriLength - 1] === pageUriList[pageUriLength - 1]) {
return true;
}
if (currentUriList[currentUriLength - 2] === pageUriList[pageUriLength - 2]) {
return true;
}
return false;
};
```
> 네비게이션 포커싱 수정

- FE/src/components/review/ReviewChart.tsx
- FE/src/components/review/ReviewSprint.tsx
- FE/src/main.tsx
- FE/src/pages/ReviewPage.tsx
- FE/src/types/backlog.ts
- review 페이지 내 Task 삭제/수정이 즉각적으로 반영되지 않는 문제를 해결
- review chart 내 마지막 데이터 제거
> fix: review page 버그 핫픽스

- FE/src/main.tsx
> hot-fix: 미사용 데이터로 인한 빌드 오류 수정

- FE/src/components/common/SideNavigationBar.tsx
- FE/src/components/review/ReviewChart.tsx
- FE/src/components/review/ReviewHeader.tsx
- FE/src/hooks/pages/review/useReminiscing.tsx
- FE/src/hooks/queries/sprint/usePatchSprintEnd.ts
- FE/src/pages/ReviewPage.tsx
- FE/src/pages/SprintPage.tsx
- 스프린트 완료 후 회고 페이지로 이동 시 가장 최근 스프린트 정보가 출력되지 않는 오류 수정
- 완료된 task가 차트에 반영되지 않는 오류 수정
> 회고 페이지 오류 수정

- FE/src/components/common/SideNavigationBar.tsx
- 백로그, 스프린트, 회고, navigation button 문구 수정 <br>
> 백로그, 스프린트, 회고, navigation button 문구 수정

- FE/src/components/common/NavigationButton.tsx
'break-keep' 속성을 추가하여 Navigation Button의 텍스트가 단어 기준으로 줄 바꿈 되도록 수정했습니다.
> navigation button 'break-keep' 속성 추가

- backend/src/app.service.ts
> feat: 백엔드 테스트

- .github/workflows/prod.cd.yml
- docker-compose.yml
[릴리즈 노트 Actions 작성](https://plastic-toad-cb0.notion.site/Actions-421f1cd8641d476d83da89e215dfd5f3)
- [현재 실행에 필요한 환경변수를 prod의 도커 컴포즈에 적용](https://github.com/boostcampwm2023/web10-Lesser/commit/807aed60384cc85033b2d2a7e59142bbf8529862)
- [릴리즈에 따른 프로덕션 서버 CD workflow 작성](https://github.com/boostcampwm2023/web10-Lesser/commit/90c388e9208f7ffa5d1e9321869dc03dc4e8858f)
> feat: 릴리즈에 따른 프로덕션 서버 CD workflow 작성

- docker-compose.dev.yml
- docker-compose.yml
fix: docker compose에 JWT_SECRET 환경변수 추가
> fix: docker compose에 JWT_SECRET 환경변수 추가

- backend/src/auth/controller/auth.controller.spec.ts
- backend/src/auth/controller/auth.controller.ts
- backend/src/auth/repository/tempMember.repository.ts
- backend/src/auth/service/auth.service.spec.ts
- backend/src/auth/service/auth.service.ts
- backend/src/auth/service/dto/github-user.dto.ts
- backend/src/member/entity/member.entity.ts
- backend/src/member/repository/member.repository.ts
- backend/src/member/service/member.service.ts
[회원가입 API 구현 (POST /auth/github/signup)](https://plastic-toad-cb0.notion.site/API-POST-auth-github-signup-6c67e26ecb894c53a4a735d9a6a35147)
- [Member 엔티티에 속성 추가, memberRepository에 저장하는 메서드 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/b86bc42ad4bc9b0ede03d1207a330978239a3f9c)
- [tempMemberRepository에서 uuid로 임시회원 조회하는 메서드 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/2c45139be890888e6ee245e6c3bcf51f207cbaca)
- [githubSignup 서비스로직 구현, getTempMember 서비스로직 구현, saveTempMember 서비스로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/f3e644a6af46407072cabb4936260dd882da3172)
- [회원가입 컨트롤러 로직 구현](https://github.com/boostcampwm2023/web10-Lesser/commit/0f7b2a7527c9f9d3eadd9e033e1ba00df5e9f5a7)
- [요청으로 들어온 tempIdToken과 temp_member 테이블에 저장된 tempIdToken이 다르면 401 에러 …
> feat: 회원가입 API 구현

- backend/src/main.ts
[개발서버가 다른 origin에 대해 CORS 허용하도록 수정](https://plastic-toad-cb0.notion.site/origin-CORS-79ba5a2dc74144f0845cfde143fcfc61?pvs=74)
> feat: 개발서버가 다른 origin에 대해 CORS 허용하도록 수정

- backend/package-lock.json
- backend/package.json
- backend/src/auth/controller/auth.controller.ts
- backend/src/auth/controller/dto/GithubAthenticationRequest.dto.ts
- backend/src/auth/controller/dto/GithubSignupRequest.dto.ts
- backend/src/main.ts
- backend/src/member/controller/member.controller.spec.ts
- backend/src/member/controller/member.controller.ts
[백엔드 서버는 잘못된 형식의 요청에 대하여 400 에러를 반환한다.](https://plastic-toad-cb0.notion.site/400-a88f4658b28545059090eb0a84cb6817)
- [Body로 온 데이터에서 요청 프로퍼티의 형식이 적절하지 않을경우 400에러 반환 로직 추가](https://github.com/boostcampwm2023/web10-Lesser/commit/085afdc9abdca2daf2fdca32902ba8bda9e98b34)
- [닉네임 유효성 검사 API 요청의 쿼리스트링 값이 없는 경우 400 에러 반환](https://github.com/boostcampwm2023/web10-Lesser/commit/5824b93c91f58c27b87a936be3aa8dda6d793a54)
- class validator, class transformer 패키지 설치
- NestJS에서 제공하는 ValidationPipe를 애플리케이션에 등록
- 클라이언트의 요청에서 DTO의 프로퍼티 외의 서버가 의도하지 않은 프로퍼티가 들어왔을때 400에러 반환
- 클라이언트의 요청에서 DTO의 프로퍼티의 형식이 적절하지 않을때 400 에러 반환
- 닉네임 유효성 검사 API의 쿼리 스트링 입력값 username 이 빈문자열(''), undefined인 경우 400 에러 반환
- Query String도 Body와 같이 DTO로 검증할 필요가 있을지에 대한 고민
- Query String으로 오는 데이터는 Body로 오는 데이터와 다르게 컨트롤러 로직 내부에서 간단하게 처리하기로 …
> feat: Bad Request Validation

- backend/test/auth/github-authentication.e2e-spec.ts
- backend/test/member/get-member.e2e-spec.ts
- backend/test/project/get-project.e2e-spec.ts
- backend/test/setup.ts
- 유저를 생성하는 서비스를 사용하지 않고 API를 사용해 유저를 생성하도록 변경
> test: setup 모듈에서 유저를 생성하는 메서드 변경

- frontend/package.json
- frontend/src/components/projects/ProjectCard.tsx
- frontend/src/components/projects/ProjectList.tsx
- frontend/src/components/projects/ProjectsSideBar.tsx
- frontend/src/constants/projects.ts
- frontend/src/pages/error/CommonErrorPage.tsx
- frontend/src/types/authDTO.ts
- frontend/tailwind.config.js
- frontend/yarn.lock
- localStorage에 저장되어 있는 사용자의 데이터를 가져와서 projectPage에서 가지고 오도록 설계
- project page 디자인 수정
- localStorage에 저장되어 있는 사용자 정보를 서버로부터 가지고 와서 화면에 출력
- profile URL의 디자인 규격이 맞지 않아서, 해당 이미지의 사이즈를 조정하는 코드 작성
- username이 배치되어 있는 곳의 gap 사이즈가 맞지 않는 점을 수정
- project page의 디자인 중, 그림자가 잘리는 현상이 발생해서 project card의 그림자 효과를 제거
- project page의 사이드 바와 리스트의 규격이 맞지 않는 점을 수정
- scroll bar가 현재 디자인과 맞지 않아서, scrollbar를 제거
> feat : member 데이터 출력

- frontend/src/components/landing/LandingLinkModal.tsx
- Modal Z-index를 최상위로 수정하여 버튼이 Modal 위로 올라오는 현상 수정
> fix : Modal Z-index 수정

- frontend/src/components/backlog/EpicDropdown.tsx
- frontend/src/components/backlog/StoryBlock.tsx
- frontend/src/components/backlog/StoryCreateForm.tsx
- frontend/src/components/backlog/TaskBlock.tsx
- frontend/src/components/backlog/TaskCreateForm.tsx
- frontend/src/hooks/pages/backlog/useBacklogInputChange.ts
- frontend/src/hooks/pages/backlog/useBacklogSocket.ts
- frontend/src/pages/backlog/UnfinishedStoryPage.tsx
- [프로젝트 회원은 백로그에서 에픽을 조회, 생성, 수정, 삭제할 수 있다.](https://plastic-toad-cb0.notion.site/9a99103f168a4afdb4c7eafbf8cd4e18)
- 에픽 추가시 추가한 에픽이 바로 선택
- 에픽 선택 시 수정 input 엘리먼트가 표시 또는 포커스
- 에픽 생성 시 하단에 생성 가능한 버튼 표시
- 선택된 에픽 삭제 시 발생하던 문제 해결
- 존재하던 에픽에 원하는 게 없을 때 생성하고 선택하는 것이라 생각해서 이미 에픽을 선택한 경우에는 자동으로 선택되지는 않도록 했습니다.
> feat: 애픽 생성, 수정 추가 기능 구현

- .github/workflows/dev.ci.yml
[백엔드 E2E 테스트 CI과정에 포함시키기](https://plastic-toad-cb0.notion.site/E2E-CI-12bac2be7d0e43ed93484f907db39138?pvs=74)
- CI 프로세스에 백엔드 E2E테스트 추가
> test: CI과정에 백엔드 E2E테스트 추가
